// Mögliche Symptome in den einzelnen Schwangerschaftswochen
export const pregnancySymptoms: { [key: number]: string[] } = {
  4: ["Ausbleiben der Periode", "Leichte Unterleibsschmerzen", "Müdigkeit", "Empfindliche Brüste"],
  5: ["Übelkeit", "Erbrechen", "Müdigkeit", "Häufiges Wasserlassen", "Heißhunger oder Abneigungen"],
  6: ["Morgendliche Übelkeit", "Stimmungsschwankungen", "Müdigkeit", "Blähungen", "Verstopfung"],
  7: ["Übelkeit", "Erbrechen", "Extreme Müdigkeit", "Vermehrter Speichelfluss", "Kopfschmerzen"],
  8: ["Übelkeit", "Erbrechen", "Müdigkeit", "Empfindliche Brüste", "Stimmungsschwankungen"],
  9: ["Übelkeit", "Sodbrennen", "Verstopfung", "Kopfschmerzen", "Schwindel"],
  10: ["Übelkeit (lässt langsam nach)", "Verstopfung", "Blähungen", "Leichte Gewichtszunahme"],
  11: ["Vermehrter Ausfluss", "Hautveränderungen", "Zahnfleischbluten", "Nasenbluten"],
  12: ["Rückgang der Übelkeit", "Mehr Energie", "Verstopfung", "Schwindel", "Kopfschmerzen"],
  13: ["Zunehmender Appetit", "Nasenbluten", "Verstopfung", "Sodbrennen"],
  14: ["Runderes Gesicht", "Hautveränderungen", "Zahnfleischbluten", "Verstopfung"],
  15: ["Nasenbluten", "Zahnfleischbluten", "Verstopfung", "Sodbrennen", "Wadenkrämpfe"],
  16: ["Rückenschmerzen", "Sodbrennen", "Verstopfung", "Schwitzen", "Schwindel"],
  17: ["Juckreiz am Bauch", "Dehnungsstreifen", "Hämorrhoiden", "Wadenkrämpfe"],
  18: ["Rückenschmerzen", "Sodbrennen", "Verstopfung", "Schwitzen", "Schwindel"],
  19: ["Rückenschmerzen", "Sodbrennen", "Verstopfung", "Schwitzen", "Schwindel"],
  20: ["Rückenschmerzen", "Sodbrennen", "Verstopfung", "Schwitzen", "Schwindel"],
  21: ["Wassereinlagerungen", "Krampfadern", "Hämorrhoiden", "Sodbrennen", "Rückenschmerzen"],
  22: ["Dehnungsstreifen", "Juckreiz am Bauch", "Sodbrennen", "Rückenschmerzen"],
  23: ["Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Wadenkrämpfe", "Kurzatmigkeit"],
  24: ["Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Wadenkrämpfe", "Kurzatmigkeit"],
  25: ["Wassereinlagerungen", "Krampfadern", "Hämorrhoiden", "Sodbrennen", "Rückenschmerzen"],
  26: ["Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Wadenkrämpfe", "Kurzatmigkeit"],
  27: ["Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Wadenkrämpfe", "Kurzatmigkeit"],
  28: ["Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Wadenkrämpfe", "Kurzatmigkeit"],
  29: ["Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Wadenkrämpfe", "Kurzatmigkeit"],
  30: ["Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Wadenkrämpfe", "Kurzatmigkeit"],
  31: ["Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Wadenkrämpfe", "Kurzatmigkeit"],
  32: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen"],
  33: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen"],
  34: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen"],
  35: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen"],
  36: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen"],
  37: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Energieschub"],
  38: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Energieschub"],
  39: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Energieschub"],
  40: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Energieschub"],
  41: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Ungeduld"],
  42: ["Braxton-Hicks-Kontraktionen", "Sodbrennen", "Rückenschmerzen", "Schlafstörungen", "Ungeduld"]
};
