// Informationen zu den einzelnen Schwangerschaftswochen
export const pregnancyWeekInfo: { [key: number]: string } = {
  4: "Dein Baby ist jetzt eine befruchtete Eizelle und beginnt sich einzunisten.",
  5: "Der Embryo ist jetzt etwa 1–2 mm groß. Die Plazenta beginnt sich zu bilden.",
  6: "Das Herz deines Babys beginnt zu schlagen – ein riesiger Meilenstein!",
  7: "Dein Baby hat nun winzige Knospen für Arme und Beine.",
  8: "Die Gesichtszüge deines Babys beginnen sich zu entwickeln.",
  9: "Jetzt entwickeln sich die Augenlinsen und erste Bewegungen sind möglich.",
  10: "Alle Organe sind angelegt – dein Baby ist jetzt ein Fötus.",
  11: "Dein Baby misst ca. 4 cm – die Finger sind bereits sichtbar.",
  12: "Die Plazenta übernimmt nun die Versorgung – das 2. Trimester naht.",
  13: "Willkommen im zweiten Trimester! Dein Baby wächst jetzt rasant.",
  14: "Feine Härchen wachsen – dein Baby übt jetzt Mimik und Bewegung.",
  15: "Dein Baby kann jetzt hören – sprich ruhig mit ihm!",
  16: "Das Geschlecht ist jetzt oft im Ultraschall erkennbar.",
  17: "Dein Baby trainiert: Schlucken, Treten, Saugen!",
  18: "Die ersten Kindsbewegungen können spürbar sein.",
  19: "Der Gleichgewichtssinn entwickelt sich – es dreht sich viel.",
  20: "Halbzeit! Dein Baby ist etwa 25 cm lang.",
  21: "Die Haut wird dicker, dein Baby legt an Gewicht zu.",
  22: "Die Augen sind fast vollständig entwickelt.",
  23: "Die Lunge reift – erste Atembewegungen starten.",
  24: "Dein Baby hat eine Überlebenschance außerhalb der Gebärmutter.",
  25: "Die Haare auf dem Kopf sprießen, dein Baby nimmt Baby-Fett zu.",
  26: "Dein Baby reagiert nun auf Berührungen und Geräusche.",
  27: "Das letzte Trimester beginnt – die Vorbereitung läuft!",
  28: "Die Augen öffnen sich regelmäßig, es folgt dem Licht.",
  29: "Der Kopf wächst – Gehirnaktivität nimmt stark zu.",
  30: "Dein Baby wiegt über 1,3 kg und ist sehr aktiv.",
  31: "Es wird enger in deinem Bauch – dein Baby kuschelt sich ein.",
  32: "Lunge & Verdauung sind fast fertig – bald ist es bereit.",
  33: "Viele Babys drehen sich jetzt in die Geburtsposition.",
  34: "Dein Baby ist ca. 45 cm groß und wiegt rund 2,3 kg.",
  35: "Die meisten Babys liegen jetzt mit dem Kopf nach unten.",
  36: "Dein Baby trainiert Saugen & Greifen – es wiegt bis zu 2,8 kg.",
  37: "Ab jetzt gilt dein Baby als termingerecht!",
  38: "Dein Baby nimmt noch Fett zu – bereit für den ersten Atemzug.",
  39: "Bald geht's los – dein Baby ist vollständig entwickelt.",
  40: "Geburtszeit! Dein Baby macht sich auf den Weg in die Welt.",
  // Für den Fall, dass die Schwangerschaft über 40 Wochen hinausgeht
  41: "Dein Baby ist vollständig entwickelt und wartet auf den Start.",
  42: "Dein Baby ist bereit für die Welt – es wird nicht mehr lange dauern!"
};

// Kürzere Versionen der Entwicklungstexte speziell für die Anzeige im Kreis
export const pregnancyWeekCircleInfo: { [key: number]: string } = {
  4: "Einnistung der befruchteten Eizelle",
  5: "Embryo 1-2mm, Plazenta bildet sich",
  6: "Herzschlag beginnt",
  7: "Winzige Arm- und Beinknospen",
  8: "Gesichtszüge entwickeln sich",
  9: "Augenlinsen entwickeln sich",
  10: "Alle Organe sind angelegt",
  11: "4cm groß, Finger sichtbar",
  12: "Plazenta übernimmt Versorgung",
  13: "Zweites Trimester beginnt",
  14: "Feine Härchen wachsen",
  15: "Gehör entwickelt sich",
  16: "Geschlecht oft erkennbar",
  17: "Übt schlucken & saugen",
  18: "Erste Bewegungen spürbar",
  19: "Gleichgewichtssinn entwickelt",
  20: "Halbzeit! 25cm groß",
  21: "Haut wird dicker",
  22: "Augen fast vollständig",
  23: "Erste Atembewegungen",
  24: "Überlebenschance außerhalb",
  25: "Kopfhaare wachsen",
  26: "Reagiert auf Geräusche",
  27: "Drittes Trimester beginnt",
  28: "Augen öffnen sich regelmäßig",
  29: "Gehirnaktivität nimmt zu",
  30: "Über 1,3kg schwer",
  31: "Kuschelt sich ein",
  32: "Lunge fast fertig entwickelt",
  33: "Dreht sich in Geburtsposition",
  34: "45cm groß, 2,3kg schwer",
  35: "Kopf meist nach unten",
  36: "Übt Saugen & Greifen",
  37: "Gilt als termingerecht",
  38: "Bereit für ersten Atemzug",
  39: "Vollständig entwickelt",
  40: "Geburtszeit!",
  41: "Wartet auf den Start",
  42: "Bereit für die Welt"
};
