// Informationen zu den einzelnen Schwangerschaftswochen
export const pregnancyWeekInfo: { [key: number]: string } = {
  4: "Dein Baby ist jetzt eine befruchtete Eizelle und beginnt sich einzunisten.",
  5: "Der Embryo ist jetzt etwa 1–2 mm groß. Die Plazenta beginnt sich zu bilden.",
  6: "Das Herz deines Babys beginnt zu schlagen – ein riesiger Meilenstein!",
  7: "Dein Baby hat nun winzige Knospen für Arme und Beine.",
  8: "Die Gesichtszüge deines Babys beginnen sich zu entwickeln.",
  9: "Jetzt entwickeln sich die Augenlinsen und erste Bewegungen sind möglich.",
  10: "Alle Organe sind angelegt – dein Baby ist jetzt ein Fötus.",
  11: "Dein Baby misst ca. 4 cm – die Finger sind bereits sichtbar.",
  12: "Die Plazenta übernimmt nun die Versorgung – das 2. Trimester naht.",
  13: "Willkommen im zweiten Trimester! Dein Baby wächst jetzt rasant.",
  14: "Feine Härchen wachsen – dein Baby übt jetzt Mimik und Bewegung.",
  15: "Dein Baby kann jetzt hören – sprich ruhig mit ihm!",
  16: "Das Geschlecht ist jetzt oft im Ultraschall erkennbar.",
  17: "Dein Baby trainiert: Schlucken, Treten, Saugen!",
  18: "Die ersten Kindsbewegungen können spürbar sein.",
  19: "Der Gleichgewichtssinn entwickelt sich – es dreht sich viel.",
  20: "Halbzeit! Dein Baby ist etwa 25 cm lang.",
  21: "Die Haut wird dicker, dein Baby legt an Gewicht zu.",
  22: "Die Augen sind fast vollständig entwickelt.",
  23: "Die Lunge reift – erste Atembewegungen starten.",
  24: "Dein Baby hat eine Überlebenschance außerhalb der Gebärmutter.",
  25: "Die Haare auf dem Kopf sprießen, dein Baby nimmt Baby-Fett zu.",
  26: "Dein Baby reagiert nun auf Berührungen und Geräusche.",
  27: "Das letzte Trimester beginnt – die Vorbereitung läuft!",
  28: "Die Augen öffnen sich regelmäßig, es folgt dem Licht.",
  29: "Der Kopf wächst – Gehirnaktivität nimmt stark zu.",
  30: "Dein Baby wiegt über 1,3 kg und ist sehr aktiv.",
  31: "Es wird enger in deinem Bauch – dein Baby kuschelt sich ein.",
  32: "Lunge & Verdauung sind fast fertig – bald ist es bereit.",
  33: "Viele Babys drehen sich jetzt in die Geburtsposition.",
  34: "Dein Baby ist ca. 45 cm groß und wiegt rund 2,3 kg.",
  35: "Die meisten Babys liegen jetzt mit dem Kopf nach unten.",
  36: "Dein Baby trainiert Saugen & Greifen – es wiegt bis zu 2,8 kg.",
  37: "Ab jetzt gilt dein Baby als termingerecht!",
  38: "Dein Baby nimmt noch Fett zu – bereit für den ersten Atemzug.",
  39: "Bald geht's los – dein Baby ist vollständig entwickelt.",
  40: "Geburtszeit! Dein Baby macht sich auf den Weg in die Welt.",
  // Für den Fall, dass die Schwangerschaft über 40 Wochen hinausgeht
  41: "Dein Baby ist vollständig entwickelt und wartet auf den Start.",
  42: "Dein Baby ist bereit für die Welt – es wird nicht mehr lange dauern!"
};
