// Informationen zur Mutter in den einzelnen Schwangerschaftswochen
export const pregnancyMotherInfo: { [key: number]: string } = {
  4: "Dein Körper produziert jetzt das Schwangerschaftshormon HCG, das den Schwangerschaftstest positiv macht.",
  5: "Deine Brüste können empfindlicher werden und leicht anschwellen.",
  6: "Dein Blutvolumen beginnt zu steigen, um dein Baby zu versorgen.",
  7: "Deine Gebärmutter wächst und ist jetzt etwa so groß wie eine Orange.",
  8: "Dein Stoffwechsel arbeitet auf Hochtouren, was zu Müdigkeit führen kann.",
  9: "Dein Körper produziert mehr Blut, um dein Baby zu versorgen.",
  10: "Dein Uterus ist jetzt etwa so groß wie eine Grapefruit.",
  11: "Dein Bauch könnte langsam sichtbar werden, besonders bei einer zweiten Schwangerschaft.",
  12: "Die Übelkeit lässt bei vielen Frauen jetzt nach, und die Energie kehrt zurück.",
  13: "Dein Körper produziert mehr Melanin, was zu Hautveränderungen führen kann.",
  14: "Deine Gebärmutter steigt aus dem Becken auf und ist jetzt von außen tastbar.",
  15: "Dein Körper produziert mehr Öl, was zu glänzender Haut führen kann.",
  16: "Dein Bauch wird deutlicher sichtbar, und du könntest erste Bewegungen spüren.",
  17: "Dein Körper speichert mehr Fett für die Milchproduktion.",
  18: "Dein Bauchnabel könnte flacher werden oder sich nach außen wölben.",
  19: "Dein Rücken passt sich der veränderten Körperhaltung an.",
  20: "Dein Bauch ist jetzt deutlich sichtbar, und du spürst regelmäßige Bewegungen.",
  21: "Deine Haut dehnt sich weiter aus, Dehnungsstreifen können entstehen.",
  22: "Dein Körper produziert mehr Schweiß, um die erhöhte Körpertemperatur zu regulieren.",
  23: "Dein Bauchnabel könnte jetzt komplett nach außen gewölbt sein.",
  24: "Deine Gebärmutter reicht jetzt bis zum Bauchnabel.",
  25: "Dein Körper speichert mehr Wasser, was zu Schwellungen führen kann.",
  26: "Deine Wirbelsäule krümmt sich stärker, um das Gewicht auszugleichen.",
  27: "Dein Körper bereitet sich auf die Milchproduktion vor, die Brüste können tropfen.",
  28: "Deine Gebärmutter reicht jetzt etwa 7,5 cm über deinen Bauchnabel.",
  29: "Dein Körper produziert das Hormon Relaxin, das deine Gelenke lockert.",
  30: "Deine Atmung kann flacher werden, da dein Zwerchfell weniger Platz hat.",
  31: "Dein Körper speichert mehr Kalzium für die Knochenentwicklung deines Babys.",
  32: "Deine Gebärmutter reicht jetzt bis unter deine Rippen.",
  33: "Dein Körper bereitet sich auf die Geburt vor, der Muttermund kann weicher werden.",
  34: "Deine Lunge hat weniger Platz, Kurzatmigkeit kann zunehmen.",
  35: "Dein Becken lockert sich, was zu Schmerzen in der Symphyse führen kann.",
  36: "Dein Baby senkt sich möglicherweise, was den Druck auf die Lunge verringert.",
  37: "Dein Körper produziert mehr Schleim, der Schleimpfropf kann sich lösen.",
  38: "Deine Gebärmutter zieht sich gelegentlich zusammen (Braxton-Hicks-Kontraktionen).",
  39: "Dein Körper bereitet sich intensiv auf die Geburt vor, der Muttermund kann sich öffnen.",
  40: "Dein Körper ist bereit für die Geburt, die jederzeit beginnen kann.",
  41: "Dein Körper produziert weiterhin Hormone, die die Geburt einleiten sollen.",
  42: "Dein Körper ist vollständig auf die Geburt vorbereitet."
};
