// Informationen zum Partner in den einzelnen Schwangerschaftswochen
export const pregnancyPartnerInfo: { [key: number]: string } = {
  4: "Unterstütze deine Partnerin emotional, da sie möglicherweise mit gemischten Gefühlen kämpft.",
  5: "Informiere dich über Schwangerschaft und Geburt, um ein verständnisvoller Partner zu sein.",
  6: "Begleite deine Partnerin zu Arztterminen, um von Anfang an dabei zu sein.",
  7: "Hilf deiner Partnerin, gesund zu essen und auf sich zu achten.",
  8: "Übernimm mehr Haushaltsaufgaben, da deine Partnerin möglicherweise sehr müde ist.",
  9: "Zeige Verständnis für Stimmungsschwankungen und körperliche Beschwerden.",
  10: "Plane gemeinsame Entspannungsaktivitäten, um Stress abzubauen.",
  11: "Sprich mit deiner Partnerin über ihre Bedürfnisse und Ängste.",
  12: "Feiert gemeinsam das Ende des ersten Trimesters, ein wichtiger Meilenstein!",
  13: "Plane mit deiner Partnerin, wie ihr die Schwangerschaft bekannt geben wollt.",
  14: "Überlegt gemeinsam, wie ihr das Kinderzimmer gestalten möchtet.",
  15: "Sprich mit deinem Baby - es kann jetzt hören und deine Stimme erkennen lernen.",
  16: "Begleite deine Partnerin zum Ultraschall, bei dem das Geschlecht erkennbar sein könnte.",
  17: "Informiere dich über Geburtsvorbereitungskurse für Paare.",
  18: "Sei aufmerksam, wenn deine Partnerin von ersten Kindsbewegungen berichtet.",
  19: "Plane mit deiner Partnerin eine Babymoon-Reise, bevor das Reisen schwieriger wird.",
  20: "Begleite deine Partnerin zum großen Ultraschall, bei dem alle Organe überprüft werden.",
  21: "Hilf beim Einkaufen von Babyausstattung und beim Einrichten des Kinderzimmers.",
  22: "Sprich mit deiner Partnerin über eure Vorstellungen zur Geburt.",
  23: "Informiere dich über Elternzeit und finanzielle Aspekte der Elternschaft.",
  24: "Überlegt gemeinsam Namen für euer Baby.",
  25: "Unterstütze deine Partnerin bei Rückenschmerzen mit Massagen oder Wärmeanwendungen.",
  26: "Plane mit deiner Partnerin, wie ihr die Zeit nach der Geburt gestalten wollt.",
  27: "Bereite dich mental auf das letzte Trimester vor, das anstrengender sein kann.",
  28: "Hilf deiner Partnerin, sich zu entspannen und genügend zu ruhen.",
  29: "Informiere dich über die Anzeichen einer beginnenden Geburt.",
  30: "Packe gemeinsam mit deiner Partnerin die Kliniktasche.",
  31: "Plane, wie ihr ins Krankenhaus kommen werdet, wenn die Wehen einsetzen.",
  32: "Übe Atemtechniken und Entspannungsmethoden mit deiner Partnerin.",
  33: "Sprich mit deiner Partnerin über ihre Wünsche während der Geburt.",
  34: "Stelle sicher, dass alles für die Ankunft des Babys vorbereitet ist.",
  35: "Sei jederzeit erreichbar, da die Geburt nun jederzeit beginnen könnte.",
  36: "Unterstütze deine Partnerin bei den letzten Vorbereitungen für das Baby.",
  37: "Sei besonders aufmerksam für Anzeichen einer beginnenden Geburt.",
  38: "Halte das Auto betankt und die Kliniktasche griffbereit.",
  39: "Sei geduldig und unterstützend, da deine Partnerin ungeduldig werden könnte.",
  40: "Sei bereit, jederzeit ins Krankenhaus zu fahren und deine Partnerin zu unterstützen.",
  41: "Zeige Verständnis für die Ungeduld deiner Partnerin und lenke sie ab.",
  42: "Unterstütze deine Partnerin bei allen Maßnahmen, die die Geburt einleiten könnten."
};
