/** Translation boundary for the contraction tracker. */
export type ContractionLocale = 'de' | 'en' | 'es';
export const DEFAULT_CONTRACTION_LOCALE: ContractionLocale = 'de';
const de = {
  'common.error': 'Fehler', 'common.notice': 'Hinweis', 'common.success': 'Erfolg', 'common.cancel': 'Abbrechen', 'common.done': 'Fertig', 'common.delete': 'Löschen', 'common.understood': 'Verstanden', 'common.unknownError': 'Unbekannter Fehler', 'common.justNow': 'Gerade eben',
  'screen.day': 'Tagesansicht', 'screen.week': 'Wochenansicht', 'screen.month': 'Monatsansicht', 'screen.previewSubtitle': 'Vorschau-Modus: nur ansehen', 'screen.subtitle': 'Verfolge deine Wehen bis zur Geburt', 'screen.preview': 'Nur Vorschau', 'screen.title': 'Wehen-Tracker', 'preview.active': 'Nur Vorschau aktiv', 'preview.description': 'Du schaust den Schwangerschaftsmodus an. Der Wehen-Tracker ist hier gesperrt.',
  'intensity.title': 'Intensität der Wehe', 'intensity.question': 'Wie stark war die Wehe?', 'intensity.weakEmoji': '🟢 Schwach', 'intensity.mediumEmoji': '🟠 Mittel', 'intensity.strongEmoji': '🔴 Stark', 'intensity.weak': 'Schwach', 'intensity.medium': 'Mittel', 'intensity.strong': 'Stark',
  'alert.saveFailed': 'Wehe konnte nicht gespeichert werden.', 'alert.laborTitle': 'Geburtsbeginn fortgeschritten', 'alert.laborMessage': 'Deine Wehen zeigen ein konstantes Muster: Sie treten etwa alle 5 Minuten auf und halten jeweils etwa 1 Minute an. Dieses Muster besteht seit mindestens einer Stunde. Der Geburtsbeginn ist wahrscheinlich so weit fortgeschritten, dass du besser jetzt ins Krankenhaus fahren solltest.', 'alert.invalidId': 'Ungültige Wehen-ID. Bitte versuche es erneut.', 'alert.notFound': 'Die Wehe konnte nicht gefunden werden.', 'alert.deleteFailed': 'Wehe konnte nicht gelöscht werden.', 'alert.updateFailed': 'Wehe konnte nicht aktualisiert werden.', 'alert.updated': 'Die Intensität der Wehe wurde erfolgreich aktualisiert.', 'alert.loadFailed': 'Wehen konnten nicht geladen werden.', 'alert.endAfterStart': 'Die Endzeit muss nach der Startzeit liegen.',
  'sync.noUsers': 'Keine verknüpften Benutzer gefunden', 'sync.partner': 'deinem Partner', 'sync.success': 'Synchronisierung erfolgreich', 'sync.successBody': '{{count}} Wehen wurden erfolgreich mit {{name}} synchronisiert.', 'sync.active': 'Synchronisiere …', 'sync.contractions': 'Wehen werden synchronisiert …',
  'range.day': 'Tag', 'range.week': 'Woche', 'range.month': 'Monat',
  'stats.count': 'Wehen', 'stats.duration': 'Ø Dauer', 'stats.interval': 'Ø Intervall', 'stats.last': 'Letzte Wehe',
  'timer.stop': 'Wehe beenden', 'timer.stopHint': 'Timer stoppen', 'timer.start': 'Wehe starten', 'timer.startHint': 'Timer beginnen', 'timer.manual': 'Manuell', 'timer.add': 'Eintrag hinzufügen', 'timer.running': 'Wehe läuft', 'timer.ready': 'Bereit', 'timer.background': 'Timer läuft auch im Hintergrund weiter', 'timer.startPrompt': 'Tippe unten, um eine neue Wehe zu starten',
  'capture.title': 'Wehenerfassung', 'history.title': 'Wehenverlauf', 'history.syncPrefix': 'Deine Wehen werden automatisch mit', 'history.syncSuffix': ' synchronisiert.', 'history.loading': 'Wehen werden geladen …', 'history.empty': 'Noch keine Wehen im Zeitraum aufgezeichnet', 'history.emptyAll': 'Noch keine Wehen aufgezeichnet.', 'history.emptyDay': 'Keine Wehen an diesem Tag aufgezeichnet.',
  'date.today': 'Heute', 'date.yesterday': 'Gestern', 'item.contraction': 'Wehe', 'item.duration': 'Dauer:', 'item.start': 'Start:', 'item.interval': 'Abstand:', 'item.startTime': 'Startzeit:', 'item.endTime': 'Endzeit:', 'item.intensity': 'Stärke:', 'item.editShort': 'Bearb.', 'item.deleteShort': 'Lösch.',
  'item.deleteTitle': 'Wehe löschen', 'item.deleteQuestion': 'Möchtest du diese Wehe wirklich löschen?', 'item.editTitle': 'Intensität bearbeiten', 'item.editQuestion': 'Wähle die neue Intensität der Wehe:',
  'manual.title': 'Manuelle Wehe', 'manual.subtitle': 'Trage Start- und Endzeit ein', 'manual.period': '⏰ Zeitraum', 'manual.start': 'Start', 'manual.end': 'Ende', 'manual.intensity': '💪 Intensität',
} as const;
export type ContractionTranslationKey = keyof typeof de;
type Catalog = Record<ContractionTranslationKey, string>;
const en: Catalog = {
  'common.error': 'Error', 'common.notice': 'Note', 'common.success': 'Success', 'common.cancel': 'Cancel', 'common.done': 'Done', 'common.delete': 'Delete', 'common.understood': 'Got it', 'common.unknownError': 'Unknown error', 'common.justNow': 'Just now',
  'screen.day': 'Day view', 'screen.week': 'Week view', 'screen.month': 'Month view', 'screen.previewSubtitle': 'Preview mode: view only', 'screen.subtitle': 'Track your contractions until birth', 'screen.preview': 'Preview only', 'screen.title': 'Contraction tracker', 'preview.active': 'Preview only', 'preview.description': 'You are previewing pregnancy mode. The contraction tracker is locked here.',
  'intensity.title': 'Contraction intensity', 'intensity.question': 'How strong was the contraction?', 'intensity.weakEmoji': '🟢 Mild', 'intensity.mediumEmoji': '🟠 Moderate', 'intensity.strongEmoji': '🔴 Strong', 'intensity.weak': 'Mild', 'intensity.medium': 'Moderate', 'intensity.strong': 'Strong',
  'alert.saveFailed': 'The contraction could not be saved.', 'alert.laborTitle': 'Labor is progressing', 'alert.laborMessage': 'Your contractions show a consistent pattern: about every 5 minutes and lasting around 1 minute, for at least an hour. Labor may have progressed enough that you should consider going to the hospital now.', 'alert.invalidId': 'Invalid contraction ID. Please try again.', 'alert.notFound': 'The contraction could not be found.', 'alert.deleteFailed': 'The contraction could not be deleted.', 'alert.updateFailed': 'The contraction could not be updated.', 'alert.updated': 'The contraction intensity was updated.', 'alert.loadFailed': 'Contractions could not be loaded.', 'alert.endAfterStart': 'The end time must be after the start time.',
  'sync.noUsers': 'No linked users found', 'sync.partner': 'your partner', 'sync.success': 'Sync successful', 'sync.successBody': '{{count}} contractions were successfully synced with {{name}}.', 'sync.active': 'Syncing …', 'sync.contractions': 'Syncing contractions …', 'range.day': 'Day', 'range.week': 'Week', 'range.month': 'Month',
  'stats.count': 'Contractions', 'stats.duration': 'Avg. duration', 'stats.interval': 'Avg. interval', 'stats.last': 'Last contraction', 'timer.stop': 'End contraction', 'timer.stopHint': 'Stop timer', 'timer.start': 'Start contraction', 'timer.startHint': 'Start timer', 'timer.manual': 'Manual', 'timer.add': 'Add entry', 'timer.running': 'Contraction in progress', 'timer.ready': 'Ready', 'timer.background': 'The timer also continues in the background', 'timer.startPrompt': 'Tap below to start a new contraction',
  'capture.title': 'Contraction tracking', 'history.title': 'Contraction history', 'history.syncPrefix': 'Your contractions are automatically synced with', 'history.syncSuffix': '.', 'history.loading': 'Loading contractions …', 'history.empty': 'No contractions recorded in this period', 'history.emptyAll': 'No contractions recorded yet.', 'history.emptyDay': 'No contractions recorded on this day.',
  'date.today': 'Today', 'date.yesterday': 'Yesterday', 'item.contraction': 'Contraction', 'item.duration': 'Duration:', 'item.start': 'Start:', 'item.interval': 'Interval:', 'item.startTime': 'Start time:', 'item.endTime': 'End time:', 'item.intensity': 'Intensity:', 'item.editShort': 'Edit', 'item.deleteShort': 'Delete',
  'item.deleteTitle': 'Delete contraction', 'item.deleteQuestion': 'Do you really want to delete this contraction?', 'item.editTitle': 'Edit intensity', 'item.editQuestion': 'Choose the new contraction intensity:',
  'manual.title': 'Manual contraction', 'manual.subtitle': 'Enter the start and end time', 'manual.period': '⏰ Time period', 'manual.start': 'Start', 'manual.end': 'End', 'manual.intensity': '💪 Intensity',
};
const es: Catalog = {
  'common.error': 'Error', 'common.notice': 'Aviso', 'common.success': 'Éxito', 'common.cancel': 'Cancelar', 'common.done': 'Listo', 'common.delete': 'Eliminar', 'common.understood': 'Entendido', 'common.unknownError': 'Error desconocido', 'common.justNow': 'Ahora mismo',
  'screen.day': 'Vista diaria', 'screen.week': 'Vista semanal', 'screen.month': 'Vista mensual', 'screen.previewSubtitle': 'Modo de vista previa: solo lectura', 'screen.subtitle': 'Registra tus contracciones hasta el parto', 'screen.preview': 'Solo vista previa', 'screen.title': 'Seguimiento de contracciones', 'preview.active': 'Solo vista previa', 'preview.description': 'Estás viendo el modo embarazo. Aquí el seguimiento de contracciones está bloqueado.',
  'intensity.title': 'Intensidad de la contracción', 'intensity.question': '¿Qué intensidad tuvo la contracción?', 'intensity.weakEmoji': '🟢 Suave', 'intensity.mediumEmoji': '🟠 Media', 'intensity.strongEmoji': '🔴 Fuerte', 'intensity.weak': 'Suave', 'intensity.medium': 'Media', 'intensity.strong': 'Fuerte',
  'alert.saveFailed': 'No se pudo guardar la contracción.', 'alert.laborTitle': 'El parto está avanzando', 'alert.laborMessage': 'Tus contracciones muestran un patrón constante: aparecen cada 5 minutos y duran alrededor de 1 minuto desde hace al menos una hora. Es posible que el parto haya avanzado lo suficiente como para ir ahora al hospital.', 'alert.invalidId': 'El identificador de la contracción no es válido. Inténtalo de nuevo.', 'alert.notFound': 'No se encontró la contracción.', 'alert.deleteFailed': 'No se pudo eliminar la contracción.', 'alert.updateFailed': 'No se pudo actualizar la contracción.', 'alert.updated': 'Se ha actualizado la intensidad de la contracción.', 'alert.loadFailed': 'No se pudieron cargar las contracciones.', 'alert.endAfterStart': 'La hora de fin debe ser posterior a la de inicio.',
  'sync.noUsers': 'No se encontraron usuarios vinculados', 'sync.partner': 'tu pareja', 'sync.success': 'Sincronización completada', 'sync.successBody': 'Se han sincronizado {{count}} contracciones con {{name}}.', 'sync.active': 'Sincronizando …', 'sync.contractions': 'Sincronizando contracciones …', 'range.day': 'Día', 'range.week': 'Semana', 'range.month': 'Mes',
  'stats.count': 'Contracciones', 'stats.duration': 'Duración media', 'stats.interval': 'Intervalo medio', 'stats.last': 'Última contracción', 'timer.stop': 'Finalizar contracción', 'timer.stopHint': 'Detener temporizador', 'timer.start': 'Iniciar contracción', 'timer.startHint': 'Iniciar temporizador', 'timer.manual': 'Manual', 'timer.add': 'Añadir entrada', 'timer.running': 'Contracción en curso', 'timer.ready': 'Preparada', 'timer.background': 'El temporizador continúa en segundo plano', 'timer.startPrompt': 'Toca abajo para iniciar una nueva contracción',
  'capture.title': 'Registro de contracciones', 'history.title': 'Historial de contracciones', 'history.syncPrefix': 'Tus contracciones se sincronizan automáticamente con', 'history.syncSuffix': '.', 'history.loading': 'Cargando contracciones …', 'history.empty': 'No hay contracciones registradas en este periodo', 'history.emptyAll': 'Aún no hay contracciones registradas.', 'history.emptyDay': 'No hay contracciones registradas este día.',
  'date.today': 'Hoy', 'date.yesterday': 'Ayer', 'item.contraction': 'Contracción', 'item.duration': 'Duración:', 'item.start': 'Inicio:', 'item.interval': 'Intervalo:', 'item.startTime': 'Hora de inicio:', 'item.endTime': 'Hora de fin:', 'item.intensity': 'Intensidad:', 'item.editShort': 'Editar', 'item.deleteShort': 'Eliminar',
  'item.deleteTitle': 'Eliminar contracción', 'item.deleteQuestion': '¿Seguro que quieres eliminar esta contracción?', 'item.editTitle': 'Editar intensidad', 'item.editQuestion': 'Elige la nueva intensidad de la contracción:',
  'manual.title': 'Contracción manual', 'manual.subtitle': 'Introduce las horas de inicio y fin', 'manual.period': '⏰ Periodo', 'manual.start': 'Inicio', 'manual.end': 'Fin', 'manual.intensity': '💪 Intensidad',
};
export const CONTRACTION_TRANSLATIONS: Record<ContractionLocale, Catalog> = { de, en, es };
export const getContractionLocaleTag = (locale: ContractionLocale) => ({ de: 'de-DE', en: 'en-US', es: 'es-ES' })[locale];
export const translateContractionText = (
  locale: ContractionLocale,
  key: ContractionTranslationKey,
  params?: Record<string, string | number>,
) => {
  const value = CONTRACTION_TRANSLATIONS[locale]?.[key] ?? de[key] ?? key;
  if (!params) return value;

  return Object.entries(params).reduce(
    (result, [name, replacement]) => result.replace(new RegExp(`\\{\\{${name}\\}\\}`, 'g'), String(replacement)),
    value,
  );
};
