/** Translation boundary for the Our Day tracker. */
export type DailyLocale = 'de' | 'en' | 'es';
export const DEFAULT_DAILY_LOCALE: DailyLocale = 'de';
const de = {
  'preview.message': 'Du bist im Babymodus zur Vorschau. Tracking ist hier nur nach der Geburt möglich.', 'preview.title': 'Nur Vorschau', 'preview.active': 'Nur Vorschau aktiv', 'preview.banner': 'Du schaust den Babymodus an. Einträge, Timer und Bearbeitung sind gesperrt.', 'screen.title': 'Unser Tag', 'screen.subtitle': 'Euer Tag – voller kleiner Meilensteine ✨', 'screen.previewSubtitle': 'Vorschau-Modus: nur ansehen',
  'action.breast': '🤱 Stillen', 'action.bottle': '🍼 Fläschchen', 'action.pump': '🥛 Abpumpen', 'action.water': '🚰 Wasser', 'action.solids': '🥄 Beikost', 'action.diaper': '🧷 Wickeln', 'action.running': '• läuft seit',
  'feeding.breast': 'Stillen', 'feeding.bottle': 'Fläschchen', 'feeding.pump': 'Abpumpen', 'feeding.water': 'Wasser', 'feeding.solids': 'Beikost', 'diaper.wet': 'Nass', 'diaper.dirty': 'Voll', 'diaper.both': 'Beides',
  'empty.today': 'Heute noch nichts erfasst', 'empty.entry': 'Noch kein Eintrag', 'empty.solids': 'Noch keine Beikost', 'quick.minimumTitle': 'Mindestens eine Quick Action', 'quick.minimumMessage': 'Eine Quick Action muss sichtbar bleiben.', 'quick.restoreTitle': 'Quick Action einblenden', 'quick.restoreQuestion': 'Welche Action soll wieder sichtbar sein?', 'quick.hiddenCount': '{{count}} verborgen',
  'common.cancel': 'Abbrechen', 'common.back': 'Zurück', 'common.done': 'Fertig', 'common.saved': 'Gespeichert', 'common.error': 'Fehler', 'common.notice': 'Hinweis', 'common.success': 'Erfolg', 'common.delete': 'Löschen', 'common.unknownError': 'Unbekannter Fehler',
  'alert.vitaminFailed': 'Der Vitamin-D-Status konnte nicht gespeichert werden.', 'alert.noBabyTitle': 'Kein Kind ausgewählt', 'alert.noBaby': 'Bitte wähle zuerst ein Kind aus.', 'alert.otherUnavailable': 'Sonstige Einträge sind in der neuen Ansicht nicht verfügbar.', 'alert.deleteTitle': 'Eintrag löschen', 'alert.deleteQuestion': 'Möchtest du diesen Eintrag wirklich löschen?', 'alert.deleted': 'Eintrag gelöscht! 🗑️',
  'view.day': 'Tag', 'view.week': 'Woche', 'view.month': 'Monat', 'view.dayTitle': 'Tagesansicht', 'view.weekTitle': 'Wochenübersicht', 'view.monthTitle': 'Monatsübersicht', 'week.diapers': 'Wickeln diese Woche', 'week.meals': 'Mahlzeiten diese Woche', 'week.summary': 'Wochenzusammenfassung', 'month.calendar': 'Aktivitätskalender',
  'summary.meals': 'Mahlzeiten', 'summary.diapers': 'Windeln', 'summary.noMeal': 'Keine Mahlzeit heute', 'summary.never': 'Nie', 'summary.mealsAccessibility': 'Mahlzeitenübersicht öffnen', 'summary.tap': 'Tippe für die Übersicht', 'summary.diaper': 'Wickeln', 'summary.last': 'Letzter:',
  'timer.cancelTitle': 'Timer abbrechen', 'timer.cancelQuestion': 'Willst du den laufenden Eintrag wirklich verwerfen?', 'timer.no': 'Nein', 'timer.discard': 'Ja, verwerfen',
  'vitamin.title': 'Vitamin D', 'vitamin.done': 'Heute erledigt', 'vitamin.open': 'Heute offen', 'vitamin.dayDone': 'Tag erledigt', 'vitamin.dayOpen': 'Tag offen', 'vitamin.resetAccessibility': 'Vitamin-D-Eintrag zurücksetzen', 'vitamin.markAccessibility': 'Vitamin D als gegeben markieren', 'vitamin.given': 'Vitamin D gegeben', 'vitamin.notGiven': 'Vitamin D noch offen', 'vitamin.documented': 'Vitamin D dokumentiert', 'vitamin.pending': 'Vitamin D offen',
  'section.metrics': 'Kennzahlen', 'section.recipes': 'BLW-Rezepte entdecken', 'section.timeline': 'Timeline', 'section.createAccessibility': 'Tippe auf ein Symbol, um einen Eintrag zu erstellen', 'meals.title': 'Mahlzeiten im Überblick', 'meals.eyebrow': 'HEUTE ERFASST', 'meals.one': 'Eintrag rund um Mahlzeiten', 'meals.other': 'Einträge rund um Mahlzeiten', 'meals.empty': 'Noch keine Mahlzeit an diesem Tag dokumentiert', 'meals.description': 'Schnell sehen, was gegessen, getrunken oder abgepumpt wurde.', 'meals.latest': 'Letzte Aktivität um {{time}} Uhr',
  'input.noFeedingTitle': 'Keine Fütterungsarten sichtbar', 'input.noFeedingBody': 'Blende mindestens eine Fütterungs-Quick-Action wieder ein.', 'input.noDiaperTitle': 'Keine Windelarten sichtbar', 'input.noDiaperBody': 'Blende mindestens eine Windel-Quick-Action wieder ein.',
  'input.invalidTemperatureTitle': 'Ungültige Temperatur', 'input.invalidTemperatureBody': 'Bitte gib eine Temperatur zwischen 30 und 45 °C ein.', 'input.invalidDoseTitle': 'Ungültige Dosis', 'input.invalidDoseBody': 'Bitte gib eine gültige Dosis in mg ein (z. B. 125).',
  'input.start': 'Start', 'input.end': 'Ende', 'input.timerRunning': 'Timer läuft', 'input.timerHint': 'Stoppe später, Ende wird gesetzt', 'input.runningUntilStop': 'Läuft, bis du stoppst', 'input.saveWithoutTimer': 'Ohne Timer speichern',
  'input.newFeeding': 'Neue Fütterung', 'input.feedingType': 'Art der Fütterung', 'input.allFeedingHidden': 'Alle Fütterungsarten sind aktuell ausgeblendet.', 'input.separateEntry': 'Separater Eintrag', 'input.waterNotice': 'Wasser wird dokumentiert, aber nicht als Fütterung oder Mahlzeit mitgezählt.', 'input.pumpNotice': 'Abpumpen wird dokumentiert, aber nicht als Fütterung oder Mahlzeit mitgezählt.',
  'input.pumpSideHint': 'Wähle die Seite, von der abgepumpt wurde.', 'input.breastSideHint': 'Wähle die Seite, auf der gestillt wurde.', 'input.chooseRecipe': 'Rezept wählen', 'input.chooseRecipeOptional': 'Rezept auswählen (optional)', 'input.loadingRecipes': 'Lade Rezepte …', 'input.noRecipes': 'Keine Rezepte gefunden', 'input.recipeHint': 'Der gewählte Rezepttitel erscheint als Hinweis in der Timeline.',
  'input.feverMeasured': 'Fieber gemessen', 'input.temperature': 'Temperatur (°C)', 'input.suppositoryGiven': 'Zäpfchen gegeben', 'input.dose': 'Dosis (mg)', 'input.diaperHint': 'Wähle aus, was auf die Windel zutrifft.', 'input.details': 'Details hinzufügen …', 'input.deleteEntry': '🗑️ Eintrag löschen',
  'input.left': 'Links', 'input.right': 'Rechts', 'input.both': 'Beide', 'input.amount': 'Menge', 'input.side': 'Seite', 'input.notes': 'Notizen',
  'input.period': 'Zeitraum', 'input.time': 'Zeitpunkt', 'input.open': 'Offen', 'input.timerOptional': 'Timer optional mitlaufen lassen', 'input.diaper': 'Wickeln', 'input.newEntry': 'Neuer Eintrag', 'input.documentedSeparately': 'Wird separat dokumentiert', 'input.enterDetails': 'Details eingeben',
  'input.pumpedAmount': 'Abgepumpte Menge (ml)', 'input.drunkAmount': 'Getrunkene Menge (ml)', 'input.amountMl': 'Menge (ml)', 'input.formulaQuestion': 'Welches Milchpulver? (optional)', 'input.automatic': 'Automatisch', 'input.noFormula': 'Kein Pulver (Muttermilch)', 'input.blwRecipes': 'BLW-Rezepte', 'input.recipe': 'Rezept', 'input.months': 'Monate',
  'input.diaperType': 'Art der Windel', 'input.allDiaperHidden': 'Alle Windelarten sind aktuell ausgeblendet.', 'input.diaperQuestion': 'Welche Windeln? (optional)', 'input.yesTemperature': 'Ja, Temperatur eintragen', 'input.optional': 'Optional', 'input.enterValue': 'Wert eingeben', 'input.yesDose': 'Ja, Dosis eintragen',
  'card.bottle': 'Flasche', 'card.sleep': 'Schlaf', 'card.other': 'Sonstiges', 'card.breast': 'Brust', 'card.fever': 'Fieber gemessen', 'card.suppository': 'Zäpfchen', 'card.suppositoryGiven': 'Zäpfchen gegeben',
  'voice.title': 'Per Sprache eintragen', 'voice.subtitle': 'Schlaf, Füttern & Windeln einfach einsprechen', 'voice.microphone': 'Mikrofon', 'voice.permission': 'Bitte erlaube den Mikrofonzugriff, um Einträge einzusprechen.', 'voice.recording': 'Aufnahme', 'voice.startFailed': 'Die Aufnahme konnte nicht gestartet werden.', 'voice.tooShortTitle': 'Aufnahme zu kurz', 'voice.tooShortBody': 'Halte den Moment kurz fest — sprich z. B. was, wann und wie viel passiert ist.', 'voice.readFailed': 'Die Aufnahme konnte nicht gelesen werden.', 'voice.entry': 'Sprach-Eintrag', 'voice.processFailed': 'Die Aufnahme konnte nicht verarbeitet werden.', 'voice.invalidTimeTitle': 'Ungültige Zeit',
  'voice.chooseFeeding': 'Fütterung auswählen', 'voice.chooseFeedingBody': 'Bitte bestätige, ob gestillt oder ein Fläschchen gegeben wurde.', 'voice.chooseFeedingFirst': 'Bitte bestätige zuerst, ob gestillt oder ein Fläschchen gegeben wurde.', 'voice.invalidStart': 'Bitte wähle eine gültige Startzeit.', 'voice.invalidEnd': 'Die Endzeit darf nicht vor der Startzeit liegen.', 'voice.invalidAmountTitle': 'Ungültige Menge', 'voice.invalidAmountBody': 'Bitte gib eine gültige Menge in ml ein.', 'voice.login': 'Bitte melde dich an, um Einträge zu speichern.', 'voice.partialSave': '{{saved}} Einträge gespeichert, {{failed}} fehlgeschlagen.', 'voice.saveFailed': 'Die Einträge konnten nicht gespeichert werden.',
  'voice.idleHint': 'Sprich einfach ein, was passiert ist — zum Beispiel:', 'voice.example': 'hat um halb drei 120 ml Fläschchen getrunken und wurde frisch gewickelt.', 'voice.tap': 'Tippen zum Aufnehmen', 'voice.running': 'Aufnahme läuft … (max. 1 Minute)', 'voice.edit': 'Eintrag ändern', 'voice.editHint': 'Prüfe die Details vor dem Speichern.', 'voice.closeEdit': 'Bearbeitung schließen', 'voice.kind': 'Art', 'voice.startTime': 'Startzeit', 'voice.endTime': 'Endzeit', 'voice.change': 'Ändern', 'voice.removeEnd': 'Endzeit entfernen', 'voice.addEnd': '+ Endzeit hinzufügen', 'voice.feeding': 'Fütterung', 'voice.amountOptional': 'Menge (optional)', 'voice.amountA11y': 'Menge in Millilitern', 'voice.noteOptional': 'Notiz (optional)', 'voice.notePlaceholder': 'Notiz ergänzen', 'voice.apply': 'Änderung übernehmen',
  'voice.none': 'Ich konnte keinen Eintrag erkennen. Versuch es gern noch einmal mit Zeit und Aktivität.', 'voice.newRecording': 'Neue Aufnahme', 'voice.detected': 'Erkannte Einträge', 'voice.selected': 'ausgewählt', 'voice.notSelected': 'nicht ausgewählt', 'voice.milkQuestion': 'Stillen oder Fläschchen?', 'voice.milkHint': 'Die Spracheingabe war nicht eindeutig. Bitte bestätige die Fütterung.', 'voice.suggested': 'Zuletzt häufiger', 'voice.editA11y': '{{title}} ändern', 'voice.saveOne': 'Eintrag speichern', 'voice.saveMany': '{{count}} Einträge speichern', 'voice.processing': 'Ich höre mir das kurz an …', 'voice.saving': 'Einträge werden gespeichert …',
  'voice.rateLimit': 'Du hast gerade viele Aufnahmen gemacht. Bitte versuche es später noch einmal.', 'voice.notEnabled': 'Sprach-Logging ist für dein Konto noch nicht freigeschaltet.', 'voice.tooLong': 'Die Aufnahme ist zu lang. Bitte halte dich an maximal eine Minute.', 'voice.serverUnexpected': 'Unerwartete Antwort vom Server. Bitte versuche es erneut.', 'voice.yesterday': 'Gestern, ', 'voice.sleep': 'Schlaf', 'voice.sleepTimer': 'Schlaf · Timer läuft', 'voice.diaper': 'Windel', 'voice.dirty': 'Stuhlgang', 'voice.wetDirty': 'Nass + Stuhlgang', 'voice.fedBreast': 'Gestillt', 'voice.pumpedMilk': 'Abgepumpte Milch', 'voice.waterTea': 'Wasser/Tee', 'voice.left': 'Links', 'voice.right': 'Rechts', 'voice.bothSides': 'beide Seiten',
  'daily.saveFeedingFailed': 'Fehler beim Speichern der Fütterung', 'daily.saveFailed': 'Fehler beim Speichern', 'daily.timerStopped': 'Timer gestoppt! ⏹️', 'daily.lastBottleMinutes': '🍼 Letzte Flasche vor {{minutes}} Min.', 'daily.lastBottleHours': '🍼 Letzte Flasche vor {{hours}} Std.', 'daily.lastBottleHoursMinutes': '🍼 Letzte Flasche vor {{hours}} Std. {{minutes}} Min.',
  'daily.running': '{{name}} läuft', 'daily.saved': '{{name}} gespeichert', 'daily.timerStarted': 'Timer gestartet …', 'daily.noTimer': 'Eintrag ohne Timer gesichert.', 'daily.takeTime': 'Nimm dir Zeit. Genieße diese besonderen Momente.', 'daily.breastHint': 'Du gibst deinem Baby alles, was es braucht', 'daily.bottleCalm': 'Ganz in Ruhe – du machst das super.', 'daily.stopTogether': 'Stoppe, wenn ihr fertig seid', 'daily.bottleHint': 'Nähe und Ernährung – perfekt kombiniert', 'daily.timerUntilStop': 'Timer läuft mit, bis du stoppst.', 'daily.solidsSaved': 'Jeder Löffel ein kleiner Fortschritt.', 'daily.solidsHint': 'Weiter so – ihr wachst gemeinsam!', 'daily.pumpBody': 'Die abgepumpte Milch ist jetzt dokumentiert.', 'daily.pumpHint': 'So behältst du Menge und Zeitpunkt im Blick', 'daily.waterBody': 'Die Wasseraufnahme ist jetzt dokumentiert.', 'daily.waterHint': 'So behältst du die Trinkmenge im Blick', 'daily.diaperFresh': 'Alles frisch – wohlfühlen ist wichtig.', 'daily.stopSingle': 'Stoppe, wenn du fertig bist', 'daily.diaperHint': 'Danke für deine liebevolle Fürsorge',
  'daily.lastAt': 'Zuletzt um {{time}} Uhr', 'daily.documented': '{{count}}× dokumentiert', 'daily.totalMl': '{{amount}} ml insgesamt', 'daily.drunkMl': '{{amount}} ml getrunken', 'daily.offered': '{{count}}× angeboten', 'daily.total': '{{duration}} gesamt', 'daily.pumpedMl': '{{amount}} ml abgepumpt', 'daily.bottleCount': 'Flasche {{count}}×',
} as const;
export type DailyTranslationKey = keyof typeof de; type Catalog = Record<DailyTranslationKey, string>;
const en: Catalog = Object.fromEntries(Object.keys(de).map((key) => [key, key])) as Catalog;
Object.assign(en, {
  'preview.message': 'You are previewing baby mode. Tracking is available after birth.', 'preview.title': 'Preview only', 'preview.active': 'Preview only', 'preview.banner': 'You are previewing baby mode. Entries, timers, and editing are locked.', 'screen.title': 'Our day', 'screen.subtitle': 'Your day, full of little milestones ✨', 'screen.previewSubtitle': 'Preview mode: view only',
  'action.breast': '🤱 Breastfeed', 'action.bottle': '🍼 Bottle', 'action.pump': '🥛 Pump', 'action.water': '🚰 Water', 'action.solids': '🥄 Solids', 'action.diaper': '🧷 Diaper', 'action.running': '• running since', 'feeding.breast': 'Breastfeeding', 'feeding.bottle': 'Bottle', 'feeding.pump': 'Pumping', 'feeding.water': 'Water', 'feeding.solids': 'Solids', 'diaper.wet': 'Wet', 'diaper.dirty': 'Dirty', 'diaper.both': 'Both',
  'empty.today': 'Nothing logged today', 'empty.entry': 'No entry yet', 'empty.solids': 'No solids yet', 'quick.minimumTitle': 'At least one quick action', 'quick.minimumMessage': 'One quick action must remain visible.', 'quick.restoreTitle': 'Show quick action', 'quick.restoreQuestion': 'Which action should be shown again?', 'quick.hiddenCount': '{{count}} hidden', 'common.cancel': 'Cancel', 'common.back': 'Back', 'common.done': 'Done', 'common.saved': 'Saved', 'common.error': 'Error', 'common.notice': 'Note', 'common.success': 'Success', 'common.delete': 'Delete', 'common.unknownError': 'Unknown error',
  'alert.vitaminFailed': 'The Vitamin D status could not be saved.', 'alert.noBabyTitle': 'No child selected', 'alert.noBaby': 'Please choose a child first.', 'alert.otherUnavailable': 'Other entries are not available in the new view.', 'alert.deleteTitle': 'Delete entry', 'alert.deleteQuestion': 'Do you really want to delete this entry?', 'alert.deleted': 'Entry deleted! 🗑️',
  'view.day': 'Day', 'view.week': 'Week', 'view.month': 'Month', 'view.dayTitle': 'Day view', 'view.weekTitle': 'Week overview', 'view.monthTitle': 'Month overview', 'week.diapers': 'Diapers this week', 'week.meals': 'Feedings this week', 'week.summary': 'Weekly summary', 'month.calendar': 'Activity calendar', 'summary.meals': 'Feedings', 'summary.diapers': 'Diapers', 'summary.noMeal': 'No feeding today', 'summary.never': 'Never', 'summary.mealsAccessibility': 'Open feeding overview', 'summary.tap': 'Tap for the overview', 'summary.diaper': 'Diaper', 'summary.last': 'Last:',
  'timer.cancelTitle': 'Cancel timer', 'timer.cancelQuestion': 'Discard the running entry?', 'timer.no': 'No', 'timer.discard': 'Yes, discard', 'vitamin.title': 'Vitamin D', 'vitamin.done': 'Done today', 'vitamin.open': 'Still open today', 'vitamin.dayDone': 'Day complete', 'vitamin.dayOpen': 'Day open', 'vitamin.resetAccessibility': 'Reset Vitamin D entry', 'vitamin.markAccessibility': 'Mark Vitamin D as given', 'vitamin.given': 'Vitamin D given', 'vitamin.notGiven': 'Vitamin D still open', 'vitamin.documented': 'Vitamin D documented', 'vitamin.pending': 'Vitamin D open', 'section.metrics': 'Key figures', 'section.recipes': 'Discover BLW recipes', 'section.timeline': 'Timeline', 'section.createAccessibility': 'Tap an icon to create an entry', 'meals.title': 'Feedings at a glance', 'meals.eyebrow': 'LOGGED TODAY', 'meals.one': 'feeding entry', 'meals.other': 'feeding entries', 'meals.empty': 'No feeding documented for this day', 'meals.description': 'Quickly see what was eaten, drunk, or pumped.', 'meals.latest': 'Last activity at {{time}}',
});
const es: Catalog = Object.fromEntries(Object.keys(de).map((key) => [key, key])) as Catalog;
Object.assign(es, {
  'preview.message': 'Estás viendo el modo bebé. El registro está disponible después del nacimiento.', 'preview.title': 'Solo vista previa', 'preview.active': 'Solo vista previa', 'preview.banner': 'Estás viendo el modo bebé. Las entradas, los temporizadores y la edición están bloqueados.', 'screen.title': 'Nuestro día', 'screen.subtitle': 'Vuestro día, lleno de pequeños hitos ✨', 'screen.previewSubtitle': 'Modo de vista previa: solo lectura',
  'action.breast': '🤱 Lactancia', 'action.bottle': '🍼 Biberón', 'action.pump': '🥛 Extracción', 'action.water': '🚰 Agua', 'action.solids': '🥄 Sólidos', 'action.diaper': '🧷 Pañal', 'action.running': '• en curso desde', 'feeding.breast': 'Lactancia', 'feeding.bottle': 'Biberón', 'feeding.pump': 'Extracción', 'feeding.water': 'Agua', 'feeding.solids': 'Sólidos', 'diaper.wet': 'Mojado', 'diaper.dirty': 'Sucio', 'diaper.both': 'Ambos',
  'empty.today': 'No hay nada registrado hoy', 'empty.entry': 'Todavía no hay entradas', 'empty.solids': 'Todavía no hay sólidos', 'quick.minimumTitle': 'Al menos una acción rápida', 'quick.minimumMessage': 'Debe quedar visible una acción rápida.', 'quick.restoreTitle': 'Mostrar acción rápida', 'quick.restoreQuestion': '¿Qué acción quieres volver a mostrar?', 'quick.hiddenCount': '{{count}} ocultas', 'common.cancel': 'Cancelar', 'common.back': 'Atrás', 'common.done': 'Listo', 'common.saved': 'Guardado', 'common.error': 'Error', 'common.notice': 'Aviso', 'common.success': 'Éxito', 'common.delete': 'Eliminar', 'common.unknownError': 'Error desconocido',
  'alert.vitaminFailed': 'No se pudo guardar el estado de la vitamina D.', 'alert.noBabyTitle': 'No hay ningún niño seleccionado', 'alert.noBaby': 'Elige primero un niño.', 'alert.otherUnavailable': 'Las demás entradas no están disponibles en la nueva vista.', 'alert.deleteTitle': 'Eliminar entrada', 'alert.deleteQuestion': '¿Seguro que quieres eliminar esta entrada?', 'alert.deleted': '¡Entrada eliminada! 🗑️',
  'view.day': 'Día', 'view.week': 'Semana', 'view.month': 'Mes', 'view.dayTitle': 'Vista diaria', 'view.weekTitle': 'Vista semanal', 'view.monthTitle': 'Vista mensual', 'week.diapers': 'Pañales esta semana', 'week.meals': 'Tomas esta semana', 'week.summary': 'Resumen semanal', 'month.calendar': 'Calendario de actividad', 'summary.meals': 'Tomas', 'summary.diapers': 'Pañales', 'summary.noMeal': 'No hay tomas hoy', 'summary.never': 'Nunca', 'summary.mealsAccessibility': 'Abrir resumen de tomas', 'summary.tap': 'Toca para ver el resumen', 'summary.diaper': 'Pañal', 'summary.last': 'Último:',
  'timer.cancelTitle': 'Cancelar temporizador', 'timer.cancelQuestion': '¿Descartar la entrada en curso?', 'timer.no': 'No', 'timer.discard': 'Sí, descartar', 'vitamin.title': 'Vitamina D', 'vitamin.done': 'Hecho hoy', 'vitamin.open': 'Pendiente hoy', 'vitamin.dayDone': 'Día completado', 'vitamin.dayOpen': 'Día pendiente', 'vitamin.resetAccessibility': 'Restablecer entrada de vitamina D', 'vitamin.markAccessibility': 'Marcar vitamina D como administrada', 'vitamin.given': 'Vitamina D administrada', 'vitamin.notGiven': 'Vitamina D pendiente', 'vitamin.documented': 'Vitamina D registrada', 'vitamin.pending': 'Vitamina D pendiente', 'section.metrics': 'Indicadores', 'section.recipes': 'Descubrir recetas BLW', 'section.timeline': 'Cronología', 'section.createAccessibility': 'Toca un icono para crear una entrada', 'meals.title': 'Resumen de tomas', 'meals.eyebrow': 'REGISTRADO HOY', 'meals.one': 'entrada de alimentación', 'meals.other': 'entradas de alimentación', 'meals.empty': 'No hay ninguna toma documentada para este día', 'meals.description': 'Consulta rápidamente qué ha comido, bebido o se ha extraído.', 'meals.latest': 'Última actividad a las {{time}}',
});
Object.assign(en, {
  'input.noFeedingTitle': 'No feeding types visible', 'input.noFeedingBody': 'Show at least one feeding quick action again.', 'input.noDiaperTitle': 'No diaper types visible', 'input.noDiaperBody': 'Show at least one diaper quick action again.',
  'input.invalidTemperatureTitle': 'Invalid temperature', 'input.invalidTemperatureBody': 'Enter a temperature between 30 and 45 °C.', 'input.invalidDoseTitle': 'Invalid dose', 'input.invalidDoseBody': 'Enter a valid dose in mg (for example 125).',
  'input.start': 'Start', 'input.end': 'End', 'input.timerRunning': 'Timer running', 'input.timerHint': 'Stop later to set the end time', 'input.runningUntilStop': 'Runs until you stop it', 'input.saveWithoutTimer': 'Save without timer',
  'input.newFeeding': 'New feeding', 'input.feedingType': 'Feeding type', 'input.allFeedingHidden': 'All feeding types are currently hidden.', 'input.separateEntry': 'Separate entry', 'input.waterNotice': 'Water is documented but not counted as a feeding or meal.', 'input.pumpNotice': 'Pumping is documented but not counted as a feeding or meal.',
  'input.pumpSideHint': 'Choose the side pumped from.', 'input.breastSideHint': 'Choose the side used for breastfeeding.', 'input.chooseRecipe': 'Choose recipe', 'input.chooseRecipeOptional': 'Choose recipe (optional)', 'input.loadingRecipes': 'Loading recipes …', 'input.noRecipes': 'No recipes found', 'input.recipeHint': 'The selected recipe title appears as a note in the timeline.',
  'input.feverMeasured': 'Temperature checked', 'input.temperature': 'Temperature (°C)', 'input.suppositoryGiven': 'Suppository given', 'input.dose': 'Dose (mg)', 'input.diaperHint': 'Choose everything that applies to the diaper.', 'input.details': 'Add details …', 'input.deleteEntry': '🗑️ Delete entry',
  'input.left': 'Left', 'input.right': 'Right', 'input.both': 'Both', 'input.amount': 'Amount', 'input.side': 'Side', 'input.notes': 'Notes',
});
Object.assign(es, {
  'input.noFeedingTitle': 'No hay tipos de toma visibles', 'input.noFeedingBody': 'Vuelve a mostrar al menos una acción rápida de alimentación.', 'input.noDiaperTitle': 'No hay tipos de pañal visibles', 'input.noDiaperBody': 'Vuelve a mostrar al menos una acción rápida de pañal.',
  'input.invalidTemperatureTitle': 'Temperatura no válida', 'input.invalidTemperatureBody': 'Introduce una temperatura entre 30 y 45 °C.', 'input.invalidDoseTitle': 'Dosis no válida', 'input.invalidDoseBody': 'Introduce una dosis válida en mg (por ejemplo, 125).',
  'input.start': 'Inicio', 'input.end': 'Fin', 'input.timerRunning': 'Temporizador en curso', 'input.timerHint': 'Deténlo más tarde para fijar la hora de fin', 'input.runningUntilStop': 'Continúa hasta que lo detengas', 'input.saveWithoutTimer': 'Guardar sin temporizador',
  'input.newFeeding': 'Nueva toma', 'input.feedingType': 'Tipo de alimentación', 'input.allFeedingHidden': 'Todos los tipos de alimentación están ocultos.', 'input.separateEntry': 'Entrada independiente', 'input.waterNotice': 'El agua se documenta, pero no cuenta como toma ni comida.', 'input.pumpNotice': 'La extracción se documenta, pero no cuenta como toma ni comida.',
  'input.pumpSideHint': 'Elige el lado del que se extrajo leche.', 'input.breastSideHint': 'Elige el lado usado para amamantar.', 'input.chooseRecipe': 'Elegir receta', 'input.chooseRecipeOptional': 'Elegir receta (opcional)', 'input.loadingRecipes': 'Cargando recetas …', 'input.noRecipes': 'No se encontraron recetas', 'input.recipeHint': 'El título de la receta seleccionada aparecerá como nota en la cronología.',
  'input.feverMeasured': 'Temperatura medida', 'input.temperature': 'Temperatura (°C)', 'input.suppositoryGiven': 'Supositorio administrado', 'input.dose': 'Dosis (mg)', 'input.diaperHint': 'Elige todo lo que corresponda al pañal.', 'input.details': 'Añadir detalles …', 'input.deleteEntry': '🗑️ Eliminar entrada',
  'input.left': 'Izquierda', 'input.right': 'Derecha', 'input.both': 'Ambos', 'input.amount': 'Cantidad', 'input.side': 'Lado', 'input.notes': 'Notas',
});
Object.assign(en, {
  'input.period': 'Time period', 'input.time': 'Time', 'input.open': 'Open', 'input.timerOptional': 'Run an optional timer', 'input.diaper': 'Diaper', 'input.newEntry': 'New entry', 'input.documentedSeparately': 'Documented separately', 'input.enterDetails': 'Enter details',
  'input.pumpedAmount': 'Pumped amount (ml)', 'input.drunkAmount': 'Amount drunk (ml)', 'input.amountMl': 'Amount (ml)', 'input.formulaQuestion': 'Which formula? (optional)', 'input.automatic': 'Automatic', 'input.noFormula': 'No formula (breast milk)', 'input.blwRecipes': 'BLW recipes', 'input.recipe': 'Recipe', 'input.months': 'months',
  'input.diaperType': 'Diaper type', 'input.allDiaperHidden': 'All diaper types are currently hidden.', 'input.diaperQuestion': 'Which diapers? (optional)', 'input.yesTemperature': 'Yes, enter temperature', 'input.optional': 'Optional', 'input.enterValue': 'Enter value', 'input.yesDose': 'Yes, enter dose',
  'card.bottle': 'Bottle', 'card.sleep': 'Sleep', 'card.other': 'Other', 'card.breast': 'Breast', 'card.fever': 'Temperature checked', 'card.suppository': 'Suppository', 'card.suppositoryGiven': 'Suppository given',
});
Object.assign(es, {
  'input.period': 'Periodo', 'input.time': 'Momento', 'input.open': 'Abierto', 'input.timerOptional': 'Usar un temporizador opcional', 'input.diaper': 'Pañal', 'input.newEntry': 'Nueva entrada', 'input.documentedSeparately': 'Se documenta por separado', 'input.enterDetails': 'Introducir detalles',
  'input.pumpedAmount': 'Cantidad extraída (ml)', 'input.drunkAmount': 'Cantidad bebida (ml)', 'input.amountMl': 'Cantidad (ml)', 'input.formulaQuestion': '¿Qué leche de fórmula? (opcional)', 'input.automatic': 'Automático', 'input.noFormula': 'Sin fórmula (leche materna)', 'input.blwRecipes': 'Recetas BLW', 'input.recipe': 'Receta', 'input.months': 'meses',
  'input.diaperType': 'Tipo de pañal', 'input.allDiaperHidden': 'Todos los tipos de pañal están ocultos.', 'input.diaperQuestion': '¿Qué pañales? (opcional)', 'input.yesTemperature': 'Sí, introducir temperatura', 'input.optional': 'Opcional', 'input.enterValue': 'Introducir valor', 'input.yesDose': 'Sí, introducir dosis',
  'card.bottle': 'Biberón', 'card.sleep': 'Sueño', 'card.other': 'Otro', 'card.breast': 'Pecho', 'card.fever': 'Temperatura medida', 'card.suppository': 'Supositorio', 'card.suppositoryGiven': 'Supositorio administrado',
});
Object.assign(en, {
  'voice.title': 'Log by voice', 'voice.subtitle': 'Simply speak sleep, feeding, and diaper entries', 'voice.microphone': 'Microphone', 'voice.permission': 'Allow microphone access to speak entries.', 'voice.recording': 'Recording', 'voice.startFailed': 'The recording could not be started.', 'voice.tooShortTitle': 'Recording too short', 'voice.tooShortBody': 'Briefly say what happened, when, and how much.', 'voice.readFailed': 'The recording could not be read.', 'voice.entry': 'Voice entry', 'voice.processFailed': 'The recording could not be processed.', 'voice.invalidTimeTitle': 'Invalid time',
  'voice.chooseFeeding': 'Choose feeding', 'voice.chooseFeedingBody': 'Confirm whether this was breastfeeding or a bottle.', 'voice.chooseFeedingFirst': 'First confirm whether this was breastfeeding or a bottle.', 'voice.invalidStart': 'Choose a valid start time.', 'voice.invalidEnd': 'The end time cannot be before the start time.', 'voice.invalidAmountTitle': 'Invalid amount', 'voice.invalidAmountBody': 'Enter a valid amount in ml.', 'voice.login': 'Sign in to save entries.', 'voice.partialSave': '{{saved}} entries saved, {{failed}} failed.', 'voice.saveFailed': 'The entries could not be saved.',
  'voice.idleHint': 'Simply say what happened — for example:', 'voice.example': 'drank a 120 ml bottle at half past two and had a fresh diaper.', 'voice.tap': 'Tap to record', 'voice.running': 'Recording … (max. 1 minute)', 'voice.edit': 'Edit entry', 'voice.editHint': 'Check the details before saving.', 'voice.closeEdit': 'Close editing', 'voice.kind': 'Type', 'voice.startTime': 'Start time', 'voice.endTime': 'End time', 'voice.change': 'Change', 'voice.removeEnd': 'Remove end time', 'voice.addEnd': '+ Add end time', 'voice.feeding': 'Feeding', 'voice.amountOptional': 'Amount (optional)', 'voice.amountA11y': 'Amount in milliliters', 'voice.noteOptional': 'Note (optional)', 'voice.notePlaceholder': 'Add a note', 'voice.apply': 'Apply change',
  'voice.none': 'I could not identify an entry. Try again with a time and activity.', 'voice.newRecording': 'New recording', 'voice.detected': 'Detected entries', 'voice.selected': 'selected', 'voice.notSelected': 'not selected', 'voice.milkQuestion': 'Breastfeeding or bottle?', 'voice.milkHint': 'The voice input was ambiguous. Confirm the feeding type.', 'voice.suggested': 'More common recently', 'voice.editA11y': 'Edit {{title}}', 'voice.saveOne': 'Save entry', 'voice.saveMany': 'Save {{count}} entries', 'voice.processing': 'Listening to that now …', 'voice.saving': 'Saving entries …',
  'voice.rateLimit': 'You have made many recordings. Please try again later.', 'voice.notEnabled': 'Voice logging is not enabled for your account yet.', 'voice.tooLong': 'The recording is too long. Keep it to one minute.', 'voice.serverUnexpected': 'Unexpected server response. Please try again.', 'voice.yesterday': 'Yesterday, ', 'voice.sleep': 'Sleep', 'voice.sleepTimer': 'Sleep · Timer running', 'voice.diaper': 'Diaper', 'voice.dirty': 'Dirty', 'voice.wetDirty': 'Wet + dirty', 'voice.fedBreast': 'Breastfed', 'voice.pumpedMilk': 'Pumped milk', 'voice.waterTea': 'Water/tea', 'voice.left': 'Left', 'voice.right': 'Right', 'voice.bothSides': 'both sides',
});
Object.assign(es, {
  'voice.title': 'Registrar por voz', 'voice.subtitle': 'Dicta fácilmente sueño, tomas y pañales', 'voice.microphone': 'Micrófono', 'voice.permission': 'Permite el acceso al micrófono para dictar entradas.', 'voice.recording': 'Grabación', 'voice.startFailed': 'No se pudo iniciar la grabación.', 'voice.tooShortTitle': 'Grabación demasiado corta', 'voice.tooShortBody': 'Di brevemente qué ocurrió, cuándo y cuánto.', 'voice.readFailed': 'No se pudo leer la grabación.', 'voice.entry': 'Entrada de voz', 'voice.processFailed': 'No se pudo procesar la grabación.', 'voice.invalidTimeTitle': 'Hora no válida',
  'voice.chooseFeeding': 'Elegir alimentación', 'voice.chooseFeedingBody': 'Confirma si fue lactancia o biberón.', 'voice.chooseFeedingFirst': 'Confirma primero si fue lactancia o biberón.', 'voice.invalidStart': 'Elige una hora de inicio válida.', 'voice.invalidEnd': 'La hora de fin no puede ser anterior a la de inicio.', 'voice.invalidAmountTitle': 'Cantidad no válida', 'voice.invalidAmountBody': 'Introduce una cantidad válida en ml.', 'voice.login': 'Inicia sesión para guardar entradas.', 'voice.partialSave': '{{saved}} entradas guardadas, {{failed}} fallidas.', 'voice.saveFailed': 'No se pudieron guardar las entradas.',
  'voice.idleHint': 'Di simplemente qué ocurrió; por ejemplo:', 'voice.example': 'tomó un biberón de 120 ml a las dos y media y se le cambió el pañal.', 'voice.tap': 'Toca para grabar', 'voice.running': 'Grabando … (máx. 1 minuto)', 'voice.edit': 'Editar entrada', 'voice.editHint': 'Comprueba los detalles antes de guardar.', 'voice.closeEdit': 'Cerrar edición', 'voice.kind': 'Tipo', 'voice.startTime': 'Hora de inicio', 'voice.endTime': 'Hora de fin', 'voice.change': 'Cambiar', 'voice.removeEnd': 'Quitar hora de fin', 'voice.addEnd': '+ Añadir hora de fin', 'voice.feeding': 'Alimentación', 'voice.amountOptional': 'Cantidad (opcional)', 'voice.amountA11y': 'Cantidad en mililitros', 'voice.noteOptional': 'Nota (opcional)', 'voice.notePlaceholder': 'Añadir nota', 'voice.apply': 'Aplicar cambio',
  'voice.none': 'No pude identificar ninguna entrada. Inténtalo de nuevo con una hora y una actividad.', 'voice.newRecording': 'Nueva grabación', 'voice.detected': 'Entradas detectadas', 'voice.selected': 'seleccionado', 'voice.notSelected': 'no seleccionado', 'voice.milkQuestion': '¿Lactancia o biberón?', 'voice.milkHint': 'La entrada de voz no fue clara. Confirma el tipo de alimentación.', 'voice.suggested': 'Más frecuente últimamente', 'voice.editA11y': 'Editar {{title}}', 'voice.saveOne': 'Guardar entrada', 'voice.saveMany': 'Guardar {{count}} entradas', 'voice.processing': 'Escuchando la grabación …', 'voice.saving': 'Guardando entradas …',
  'voice.rateLimit': 'Has hecho muchas grabaciones. Inténtalo de nuevo más tarde.', 'voice.notEnabled': 'El registro por voz aún no está habilitado para tu cuenta.', 'voice.tooLong': 'La grabación es demasiado larga. Limítala a un minuto.', 'voice.serverUnexpected': 'Respuesta inesperada del servidor. Inténtalo de nuevo.', 'voice.yesterday': 'Ayer, ', 'voice.sleep': 'Sueño', 'voice.sleepTimer': 'Sueño · temporizador en curso', 'voice.diaper': 'Pañal', 'voice.dirty': 'Sucio', 'voice.wetDirty': 'Mojado + sucio', 'voice.fedBreast': 'Lactancia', 'voice.pumpedMilk': 'Leche extraída', 'voice.waterTea': 'Agua/té', 'voice.left': 'Izquierda', 'voice.right': 'Derecha', 'voice.bothSides': 'ambos lados',
});
Object.assign(en, {
  'daily.saveFeedingFailed': 'Failed to save feeding', 'daily.saveFailed': 'Failed to save', 'daily.timerStopped': 'Timer stopped! ⏹️', 'daily.lastBottleMinutes': '🍼 Last bottle {{minutes}} min ago', 'daily.lastBottleHours': '🍼 Last bottle {{hours}} hr ago', 'daily.lastBottleHoursMinutes': '🍼 Last bottle {{hours}} hr {{minutes}} min ago',
  'daily.running': '{{name}} running', 'daily.saved': '{{name}} saved', 'daily.timerStarted': 'Timer started …', 'daily.noTimer': 'Entry saved without a timer.', 'daily.takeTime': 'Take your time and enjoy these special moments.', 'daily.breastHint': 'You are giving your baby what they need', 'daily.bottleCalm': 'Take it easy – you are doing great.', 'daily.stopTogether': 'Stop when you are finished', 'daily.bottleHint': 'Closeness and nourishment, beautifully combined', 'daily.timerUntilStop': 'The timer runs until you stop it.', 'daily.solidsSaved': 'Every spoonful is a small step forward.', 'daily.solidsHint': 'Keep going – you are growing together!', 'daily.pumpBody': 'The pumped milk is now documented.', 'daily.pumpHint': 'Keep the amount and time in view', 'daily.waterBody': 'The water intake is now documented.', 'daily.waterHint': 'Keep the drinking amount in view', 'daily.diaperFresh': 'All fresh and comfortable.', 'daily.stopSingle': 'Stop when you are done', 'daily.diaperHint': 'Thank you for your loving care',
  'daily.lastAt': 'Last at {{time}}', 'daily.documented': '{{count}} logged', 'daily.totalMl': '{{amount}} ml total', 'daily.drunkMl': '{{amount}} ml drunk', 'daily.offered': '{{count}} offered', 'daily.total': '{{duration}} total', 'daily.pumpedMl': '{{amount}} ml pumped', 'daily.bottleCount': 'Bottle {{count}}×',
});
Object.assign(es, {
  'daily.saveFeedingFailed': 'Error al guardar la toma', 'daily.saveFailed': 'Error al guardar', 'daily.timerStopped': '¡Temporizador detenido! ⏹️', 'daily.lastBottleMinutes': '🍼 Último biberón hace {{minutes}} min', 'daily.lastBottleHours': '🍼 Último biberón hace {{hours}} h', 'daily.lastBottleHoursMinutes': '🍼 Último biberón hace {{hours}} h {{minutes}} min',
  'daily.running': '{{name}} en curso', 'daily.saved': '{{name}} guardado', 'daily.timerStarted': 'Temporizador iniciado …', 'daily.noTimer': 'Entrada guardada sin temporizador.', 'daily.takeTime': 'Tómate tu tiempo y disfruta estos momentos especiales.', 'daily.breastHint': 'Le das a tu bebé todo lo que necesita', 'daily.bottleCalm': 'Con calma: lo estás haciendo genial.', 'daily.stopTogether': 'Deténlo cuando hayáis terminado', 'daily.bottleHint': 'Cercanía y alimentación, una combinación perfecta', 'daily.timerUntilStop': 'El temporizador sigue hasta que lo detengas.', 'daily.solidsSaved': 'Cada cucharada es un pequeño avance.', 'daily.solidsHint': 'Seguid así: ¡crecéis juntos!', 'daily.pumpBody': 'La leche extraída ya está documentada.', 'daily.pumpHint': 'Así controlas la cantidad y el momento', 'daily.waterBody': 'La ingesta de agua ya está documentada.', 'daily.waterHint': 'Así controlas cuánto bebe', 'daily.diaperFresh': 'Todo limpio y cómodo.', 'daily.stopSingle': 'Deténlo cuando termines', 'daily.diaperHint': 'Gracias por tus cuidados',
  'daily.lastAt': 'Último a las {{time}}', 'daily.documented': '{{count}} registrados', 'daily.totalMl': '{{amount}} ml en total', 'daily.drunkMl': '{{amount}} ml bebidos', 'daily.offered': '{{count}} ofrecidos', 'daily.total': '{{duration}} en total', 'daily.pumpedMl': '{{amount}} ml extraídos', 'daily.bottleCount': 'Biberón {{count}}×',
});
export const DAILY_TRANSLATIONS: Record<DailyLocale, Catalog> = { de, en, es };
export const getDailyLocaleTag = (locale: DailyLocale) => ({ de: 'de-DE', en: 'en-US', es: 'es-ES' })[locale];
export const translateDailyText = (locale: DailyLocale, key: DailyTranslationKey, params: Record<string, string | number> = {}) =>
  (DAILY_TRANSLATIONS[locale]?.[key] ?? de[key] ?? key).replace(/\{\{(\w+)\}\}/g, (_, token: string) => String(params[token] ?? `{{${token}}}`));
