export const DEFAULT_PAYWALL_TRIAL_DAYS = 14;
export const DEFAULT_DISPLAY_MONTHLY_PRICE = 11.99;
export const DEFAULT_DISPLAY_YEARLY_PRICE = 143.88;
export const DEFAULT_DISPLAY_STANDARD_MONTHLY_PRICE = 6.5;
export const DEFAULT_DISPLAY_STANDARD_YEARLY_PRICE = 78;
export const DEFAULT_DISPLAY_LITE_MONTHLY_PRICE = 3.79;
export const DEFAULT_DISPLAY_LITE_YEARLY_PRICE = 45.48;
