export const DEFAULT_PAYWALL_TRIAL_DAYS = 14;
export const DEFAULT_DISPLAY_MONTHLY_PRICE = 11.99;
export const DEFAULT_DISPLAY_YEARLY_PRICE = 124.99;
export const DEFAULT_DISPLAY_STANDARD_MONTHLY_PRICE = 3.75;
export const DEFAULT_DISPLAY_STANDARD_YEARLY_PRICE = 39.99;
export const DEFAULT_DISPLAY_LITE_MONTHLY_PRICE = 2.99;
export const DEFAULT_DISPLAY_LITE_YEARLY_PRICE = 29.99;
