import type { AppLocale } from './localization';

const copy = {
  de: {
    billingApple: 'Abrechnung über den App Store', billingGoogle: 'Abrechnung über Google Play', billing: 'Abrechnung', store: 'dem Store', editTitle: 'Inline-Editor', previewTitle: 'Gerenderte Vorschau', editDescription: 'Tippe direkt auf einen Text in der Paywall und ändere ihn an Ort und Stelle. Ausgeblendete Pläne bleiben hier gedimmt sichtbar.', previewDescription: 'Hier siehst du die Paywall exakt so, wie Nutzer sie aktuell sehen – inklusive ausgeblendeter Pläne.', draft: 'Entwurf offen', saved: 'Alles gespeichert', loadError: 'Gespeicherte Texte konnten nicht geladen werden. Die Standardtexte sind aktiv.', resetTitle: 'Standardtexte laden', resetQuestion: 'Willst du wirklich alle Paywall-Texte auf die Standardversion zurücksetzen? Nicht gespeicherte Änderungen gehen dabei verloren.', cancel: 'Abbrechen', reset: 'Zurücksetzen', savedTitle: 'Gespeichert', savedMessage: 'Die Paywall-Texte wurden aktualisiert.', saveError: 'Die Paywall-Texte konnten nicht gespeichert werden.', header: 'Paywall-Editor', subtitle: 'Texte, Pläne & Sichtbarkeit bearbeiten', loading: 'Paywall-Konfiguration wird geladen…', adminOnly: 'Dieser Bereich ist nur für Admins mit `profiles.is_admin = true`.', lastSaved: 'Zuletzt gespeichert', noSaved: 'Noch keine gespeicherte Version gefunden.', workflow: 'Workflow', workflowEdit: 'Texte direkt in der Oberfläche anfassen und sofort prüfen.', workflowPreview: 'Sichere Ansicht zum Gegencheck, ohne Texte versehentlich zu verändern.', edit: 'Direkt bearbeiten', preview: 'Vorschau', saving: 'Speichere Änderungen…', save: 'Änderungen speichern', allSaved: 'Alles ist gespeichert', saveHint: 'Übernimmt den aktuellen Entwurf direkt für die Live-Paywall.', savedHint: 'Sobald du Texte änderst, kannst du sie hier sichern.', restoreSaved: 'Gespeicherten Stand laden', restoreSavedHint: 'Lädt die letzte gespeicherte Version und verwirft den aktuellen Entwurf.', restoreDefaultsHint: 'Setzt den Editor auf die Basisversion der Paywall zurück.', toggleTitle: 'Pläne ein- & ausblenden', toggleHint: 'Ausgeblendete Pläne verschwinden auf der Live-Paywall aus der Auswahl und aus der Vergleichstabelle.', allHidden: 'Alle Pläne sind ausgeblendet – die App zeigt in diesem Fall zur Sicherheit wieder alle Pläne an.', settings: 'Basis-Einstellungen', settingsHint: 'Trial-Dauer für die App-Logik. Alle Preise kommen direkt aus dem Store; solange ein Produkt dort fehlt, gelten die Fallback-Preise aus der App (nicht hier editierbar).', trialDays: 'Trial-Tage', premiumDescription: 'Standard plus KI-Features (Sprach-Logging, Lottis Fürsorge, Frag Lotti).', standardDescription: 'Voller Funktionsumfang ohne KI-Features.', liteDescription: 'Basis-Tracker mit Verlauf der letzten 7 Tage.',
  },
  en: {
    billingApple: 'Billed through the App Store', billingGoogle: 'Billed through Google Play', billing: 'Billing', store: 'the store', editTitle: 'Inline editor', previewTitle: 'Rendered preview', editDescription: 'Tap any text in the paywall and edit it in place. Hidden plans remain visible here with reduced opacity.', previewDescription: 'This shows the paywall exactly as users currently see it, including hidden plans.', draft: 'Draft open', saved: 'Everything saved', loadError: 'Saved copy could not be loaded. The default copy is active.', resetTitle: 'Load default copy', resetQuestion: 'Reset all paywall copy to the default version? Unsaved changes will be lost.', cancel: 'Cancel', reset: 'Reset', savedTitle: 'Saved', savedMessage: 'The paywall copy was updated.', saveError: 'The paywall copy could not be saved.', header: 'Paywall editor', subtitle: 'Edit copy, plans & visibility', loading: 'Loading paywall configuration…', adminOnly: 'This area is only available to admins with `profiles.is_admin = true`.', lastSaved: 'Last saved', noSaved: 'No saved version found yet.', workflow: 'Workflow', workflowEdit: 'Edit copy directly in the interface and review it immediately.', workflowPreview: 'Safe review mode without accidentally changing copy.', edit: 'Edit directly', preview: 'Preview', saving: 'Saving changes…', save: 'Save changes', allSaved: 'Everything is saved', saveHint: 'Publishes the current draft to the live paywall.', savedHint: 'Once you edit copy, you can save it here.', restoreSaved: 'Restore saved version', restoreSavedHint: 'Loads the last saved version and discards the current draft.', restoreDefaultsHint: 'Resets the editor to the base paywall copy.', toggleTitle: 'Show & hide plans', toggleHint: 'Hidden plans disappear from the live paywall selection and comparison table.', allHidden: 'All plans are hidden. As a safeguard, the app will show all plans.', settings: 'Base settings', settingsHint: 'Trial length for app logic. Prices come from the store; app fallback prices apply when a product is unavailable and cannot be edited here.', trialDays: 'Trial days', premiumDescription: "Standard plus AI features (voice logging, Lotti's Care, and Ask Lotti).", standardDescription: 'Full feature set without AI features.', liteDescription: 'Core trackers with the last 7 days of history.',
  },
  es: {
    billingApple: 'Facturación mediante App Store', billingGoogle: 'Facturación mediante Google Play', billing: 'Facturación', store: 'la tienda', editTitle: 'Editor integrado', previewTitle: 'Vista previa', editDescription: 'Toca un texto del muro de pago para editarlo directamente. Los planes ocultos siguen visibles aquí con menor opacidad.', previewDescription: 'Aquí ves el muro de pago tal como lo ven los usuarios, incluidos los planes ocultos.', draft: 'Borrador abierto', saved: 'Todo guardado', loadError: 'No se pudieron cargar los textos guardados. Están activos los textos predeterminados.', resetTitle: 'Cargar textos predeterminados', resetQuestion: '¿Quieres restablecer todos los textos del muro de pago? Se perderán los cambios sin guardar.', cancel: 'Cancelar', reset: 'Restablecer', savedTitle: 'Guardado', savedMessage: 'Se han actualizado los textos del muro de pago.', saveError: 'No se pudieron guardar los textos del muro de pago.', header: 'Editor del muro de pago', subtitle: 'Editar textos, planes y visibilidad', loading: 'Cargando la configuración del muro de pago…', adminOnly: 'Esta sección solo está disponible para administradores con `profiles.is_admin = true`.', lastSaved: 'Último guardado', noSaved: 'Aún no se ha encontrado una versión guardada.', workflow: 'Flujo de trabajo', workflowEdit: 'Edita los textos en la interfaz y revísalos al instante.', workflowPreview: 'Vista segura para revisar sin cambiar textos por error.', edit: 'Editar directamente', preview: 'Vista previa', saving: 'Guardando cambios…', save: 'Guardar cambios', allSaved: 'Todo está guardado', saveHint: 'Publica el borrador actual en el muro de pago.', savedHint: 'Cuando cambies un texto, podrás guardarlo aquí.', restoreSaved: 'Restaurar versión guardada', restoreSavedHint: 'Carga la última versión guardada y descarta el borrador actual.', restoreDefaultsHint: 'Restablece el editor a los textos base del muro de pago.', toggleTitle: 'Mostrar y ocultar planes', toggleHint: 'Los planes ocultos desaparecen de la selección y de la tabla comparativa.', allHidden: 'Todos los planes están ocultos. Como medida de seguridad, la app mostrará todos.', settings: 'Ajustes básicos', settingsHint: 'Duración de la prueba para la lógica de la app. Los precios proceden de la tienda; si falta un producto se usan los precios alternativos de la app, que no se editan aquí.', trialDays: 'Días de prueba', premiumDescription: 'Standard más funciones de IA (registro por voz, Cuidados de Lotti y Pregunta a Lotti).', standardDescription: 'Todas las funciones sin herramientas de IA.', liteDescription: 'Seguimiento básico con historial de los últimos 7 días.',
  },
} as const;

export const getPaywallAdminCopy = (locale: AppLocale) => copy[locale];
