/** Translation boundary for the planner overview. */
export type PlannerLocale = 'de' | 'en' | 'es';
export const DEFAULT_PLANNER_LOCALE: PlannerLocale = 'de';
const de = {
  'common.error': 'Fehler', 'common.cancel': 'Abbrechen', 'common.save': 'Speichern', 'common.delete': 'Löschen', 'common.today': 'Heute', 'common.tomorrow': 'Morgen', 'common.yesterday': 'Gestern', 'common.allDay': 'Ganztägig', 'common.open': 'Offen',
  'dayPart.morning': 'Morgen', 'dayPart.midday': 'Mittag', 'dayPart.afternoon': 'Nachmittag', 'dayPart.evening': 'Abend',
  'person.me': 'Ich', 'person.baby': 'Baby', 'person.partner': 'Partner', 'person.child': 'Kind', 'person.family': 'Familie',
  'view.day': 'Tag', 'view.week': 'Woche', 'view.month': 'Monat', 'view.dayOverview': 'Tagesübersicht', 'view.weekOverview': 'Wochenübersicht', 'view.monthOverview': 'Monatsübersicht',
  'greeting.hello': 'Hallo', 'greeting.welcome': 'Schön, dass du da bist.', 'greeting.morning': 'Guten Morgen', 'greeting.morningSub': 'Bereit für einen neuen Tag?', 'greeting.day': 'Guten Tag', 'greeting.daySub': 'Was steht heute noch an?', 'greeting.evening': 'Guten Abend', 'greeting.eveningSub': 'Lass den Tag entspannt ausklingen.', 'greeting.night': 'Gute Nacht', 'greeting.nightSub': 'Zeit zum Abschalten und Ausruhen.', 'greeting.you': 'du',
  'sync.loadFailed': 'Kalender-Sync konnte nicht geladen werden.', 'sync.changes': '{{count}} Änderungen synchronisiert', 'sync.current': 'Alles aktuell', 'sync.failed': 'Kalender-Sync ist fehlgeschlagen.', 'sync.enableFailed': 'Kalender-Sync konnte nicht aktiviert werden.', 'sync.disableFailed': 'Kalender-Sync konnte nicht deaktiviert werden.', 'sync.settingsAccessibility': 'Apple-Kalender-Sync-Einstellungen', 'sync.title': 'Apple Kalender', 'sync.ready': 'Lotti Baby · bereit', 'sync.last': 'Lotti Baby · zuletzt {{time}}', 'sync.off': 'Sync ist ausgeschaltet', 'sync.readyAction': 'Bereit zum Synchronisieren', 'sync.actionAccessibility': 'Apple Kalender jetzt synchronisieren',
  'delete.recurringTitle': 'Wiederkehrenden Eintrag löschen', 'delete.recurringQuestion': 'Soll nur dieser Tag oder die gesamte Serie gelöscht werden?', 'delete.onlyDay': 'Nur diesen Tag löschen', 'delete.series': 'Alle Wiederholungen löschen', 'delete.failed': 'Der Eintrag konnte nicht gelöscht werden.', 'delete.unexpected': 'Ein Fehler ist aufgetreten.',
  'validation.timeTitle': 'Ungültige Zeit', 'validation.timeMessage': 'Der Termin enthält keine gültige Startzeit.', 'validation.unsupportedTitle': 'Nicht unterstützt', 'validation.unsupportedMessage': 'Der Typ kann für nur einen einzelnen Serien-Tag nicht geändert werden.',
  'navigation.previousDay': 'Vorheriger Tag', 'navigation.previousWeek': 'Vorherige Woche', 'navigation.previousMonth': 'Vorheriger Monat', 'navigation.nextDay': 'Nächster Tag', 'navigation.nextWeek': 'Nächste Woche', 'navigation.nextMonth': 'Nächster Monat',
  'tasks.title': 'Aufgaben', 'tasks.open': '{{count}} offen', 'tasks.flexible': 'Flexibel', 'tasks.flexibleWith': 'Flexibel · {{name}}', 'tasks.empty': 'Keine offenen Aufgaben ohne Datum', 'tasks.hideDone': 'Erledigte Aufgaben ausblenden', 'tasks.showDone': 'Erledigte Aufgaben anzeigen', 'tasks.done': 'Erledigt',
  'calendar.week': 'Wochenplan', 'calendar.month': 'Monatskalender', 'weekday.mon': 'Mo', 'weekday.tue': 'Di', 'weekday.wed': 'Mi', 'weekday.thu': 'Do', 'weekday.fri': 'Fr', 'weekday.sat': 'Sa', 'weekday.sun': 'So',
  'capture.editTodo': 'Aufgabe bearbeiten', 'capture.editEvent': 'Termin bearbeiten', 'capture.newTodo': 'Neue Aufgabe', 'capture.newEvent': 'Neuer Termin', 'capture.details': 'Details bearbeiten', 'capture.quick': 'Schnell erfassen',
  'capture.todo': 'Aufgabe', 'capture.event': 'Termin', 'capture.title': 'Titel', 'capture.more': 'Mehr Optionen', 'capture.less': 'Weniger Optionen', 'capture.moreA11y': 'Mehr Optionen anzeigen', 'capture.lessA11y': 'Weniger Optionen anzeigen',
  'capture.for': '👤 Für', 'capture.forWhom': 'Für wen?', 'capture.repeat': '🔄 Wiederholen', 'capture.on': 'An', 'capture.off': 'Aus', 'capture.daily': 'Jeden Tag', 'capture.weekdays': 'Wochentags (Mo–Fr)',
  'capture.seriesEnd': 'Serienende', 'capture.endsOn': 'Endet am', 'capture.noEnd': 'Ohne Enddatum', 'capture.addEndDate': 'Enddatum hinzufügen', 'capture.period': 'Zeitraum', 'capture.location': 'Ort', 'capture.locationOptional': 'Ort (optional)',
  'capture.reminder': 'Erinnerung', 'capture.time': '🕒 Zeitpunkt', 'capture.due': 'Fällig', 'capture.timeRequired': 'Zeit erforderlich', 'capture.noDate': 'Kein Datum setzen', 'capture.addDate': 'Datum hinzufügen', 'capture.notes': '📝 Notizen', 'capture.notesPlain': 'Notizen', 'capture.detailsPlaceholder': 'Details hinzufügen …', 'capture.deleteEntry': '🗑️ Eintrag löschen',
  'capture.clock': '🕒 Uhrzeit', 'capture.withTime': 'Mit Uhrzeit', 'capture.from': 'Von', 'capture.to': 'Bis', 'capture.start': 'Start', 'capture.end': 'Ende', 'capture.removeEnd': 'Endzeit entfernen', 'capture.addEnd': 'Endzeit hinzufügen', 'capture.applyPeriod': 'Zeitraum übernehmen', 'capture.choose': '{{label}} wählen', 'capture.fromTime': 'ab {{time}}',
  'reminder.none': 'Keine Erinnerung', 'reminder.atStart': 'Zum Start', 'reminder.oneHour': '1 Std. vorher', 'reminder.twoHours': '2 Std. vorher', 'reminder.oneDay': '1 Tag vorher', 'reminder.minutes': '{{count}} Min. vorher',
  'capture.weekdaysMissingTitle': 'Wochentage fehlen', 'capture.weekdaysMissingBody': 'Bitte wähle mindestens einen Wochentag aus.', 'capture.invalidStart': 'Bitte wähle eine gültige Startzeit.', 'capture.invalidEnd': 'Bitte wähle eine gültige Endzeit.', 'capture.invalidTime': 'Bitte wähle einen gültigen Zeitpunkt.',
  'capture.timeMissingTitle': 'Zeit fehlt', 'capture.timeMissingBody': 'Wiederkehrende Aufgaben brauchen eine Uhrzeit oder ein Fälligkeitsdatum.', 'capture.recurringMultiDay': 'Wiederkehrende Termine können in dieser Version nur am selben Tag stattfinden.', 'capture.invalidEndDateTitle': 'Enddatum ungültig', 'capture.invalidEndDateBody': 'Das Enddatum darf nicht vor dem ersten Termin der Serie liegen.',
  'capture.changeEndTitle': 'Enddatum ändern', 'capture.changeEndBody': 'Das Enddatum gilt immer für die gesamte Serie.', 'capture.entireSeries': 'Gesamte Serie', 'capture.saveChangesTitle': 'Änderungen speichern', 'capture.saveChangesBody': 'Soll die Änderung nur für diesen Tag oder für die gesamte Serie gelten?', 'capture.onlyDay': 'Nur diesen Tag',

  'capture.color': '🎨 Farbe', 'capture.colorAuto': 'Automatisch', 'capture.colorAutoHint': 'Farbe der Person', 'color.rose': 'Rosé', 'color.coral': 'Koralle', 'color.amber': 'Bernstein', 'color.olive': 'Oliv', 'color.green': 'Grün', 'color.teal': 'Petrol', 'color.blue': 'Blau', 'color.indigo': 'Violett', 'color.berry': 'Beere', 'color.slate': 'Schiefer',
  'capture.deleteRecurringBody': 'Möchtest du nur diesen Tag oder die gesamte Serie löschen?', 'capture.deleteTitle': 'Eintrag löschen', 'capture.deleteMetadataBody': 'Die Serienmetadaten konnten nicht gelesen werden. Möchtest du diesen Eintrag wirklich löschen?', 'capture.deleteBody': 'Möchtest du diesen Eintrag wirklich löschen?',
  'widget.timelineTitle': 'Planer', 'widget.tasksTitle': 'Aufgaben', 'widget.open': 'offen', 'widget.done': 'erledigt', 'widget.flexible': 'Flexibel', 'widget.allDay': 'Ganztägig', 'widget.now': 'Jetzt', 'widget.noEventsTitle': 'Keine Termine', 'widget.noEventsHint': 'Heute ist nichts geplant', 'widget.noMoreEvents': 'Keine weiteren Termine', 'widget.noTasksTitle': 'Alles erledigt', 'widget.noTasksHint': 'Keine offenen Aufgaben', 'widget.moreItems': '+{{count}} weitere', 'widget.eventsCount': '{{count}} Termine', 'widget.signedOut': 'In Lotti Baby öffnen', 'widget.staleHint': 'Zum Aktualisieren App öffnen', 'widget.addTask': 'Aufgabe',
} as const;
export type PlannerTranslationKey = keyof typeof de;
type Catalog = Record<PlannerTranslationKey, string>;
const en: Catalog = {
  'common.error': 'Error', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.delete': 'Delete', 'common.today': 'Today', 'common.tomorrow': 'Tomorrow', 'common.yesterday': 'Yesterday', 'common.allDay': 'All day', 'common.open': 'Open', 'dayPart.morning': 'Morning', 'dayPart.midday': 'Midday', 'dayPart.afternoon': 'Afternoon', 'dayPart.evening': 'Evening', 'person.me': 'Me', 'person.baby': 'Baby', 'person.partner': 'Partner', 'person.child': 'Child', 'person.family': 'Family',
  'view.day': 'Day', 'view.week': 'Week', 'view.month': 'Month', 'view.dayOverview': 'Day overview', 'view.weekOverview': 'Week overview', 'view.monthOverview': 'Month overview', 'greeting.hello': 'Hello', 'greeting.welcome': 'It’s lovely to have you here.', 'greeting.morning': 'Good morning', 'greeting.morningSub': 'Ready for a new day?', 'greeting.day': 'Hello', 'greeting.daySub': 'What is still on the agenda today?', 'greeting.evening': 'Good evening', 'greeting.eveningSub': 'Let the day wind down gently.', 'greeting.night': 'Good night', 'greeting.nightSub': 'Time to switch off and rest.', 'greeting.you': 'you',
  'sync.loadFailed': 'Calendar sync could not be loaded.', 'sync.changes': '{{count}} changes synced', 'sync.current': 'Everything is up to date', 'sync.failed': 'Calendar sync failed.', 'sync.enableFailed': 'Calendar sync could not be enabled.', 'sync.disableFailed': 'Calendar sync could not be disabled.', 'sync.settingsAccessibility': 'Apple Calendar sync settings', 'sync.title': 'Apple Calendar', 'sync.ready': 'Lotti Baby · ready', 'sync.last': 'Lotti Baby · last synced {{time}}', 'sync.off': 'Sync is off', 'sync.readyAction': 'Ready to sync', 'sync.actionAccessibility': 'Sync Apple Calendar now',
  'delete.recurringTitle': 'Delete recurring item', 'delete.recurringQuestion': 'Delete only this day or the entire series?', 'delete.onlyDay': 'Delete this day only', 'delete.series': 'Delete all repeats', 'delete.failed': 'The item could not be deleted.', 'delete.unexpected': 'Something went wrong.', 'validation.timeTitle': 'Invalid time', 'validation.timeMessage': 'The appointment does not have a valid start time.', 'validation.unsupportedTitle': 'Not supported', 'validation.unsupportedMessage': 'The type cannot be changed for just one day in a series.',
  'navigation.previousDay': 'Previous day', 'navigation.previousWeek': 'Previous week', 'navigation.previousMonth': 'Previous month', 'navigation.nextDay': 'Next day', 'navigation.nextWeek': 'Next week', 'navigation.nextMonth': 'Next month', 'tasks.title': 'Tasks', 'tasks.open': '{{count}} open', 'tasks.flexible': 'Flexible', 'tasks.flexibleWith': 'Flexible · {{name}}', 'tasks.empty': 'No open tasks without a date', 'tasks.hideDone': 'Hide completed tasks', 'tasks.showDone': 'Show completed tasks', 'tasks.done': 'Completed', 'calendar.week': 'Week plan', 'calendar.month': 'Monthly calendar', 'weekday.mon': 'Mon', 'weekday.tue': 'Tue', 'weekday.wed': 'Wed', 'weekday.thu': 'Thu', 'weekday.fri': 'Fri', 'weekday.sat': 'Sat', 'weekday.sun': 'Sun',
  'capture.editTodo': 'Edit task', 'capture.editEvent': 'Edit event', 'capture.newTodo': 'New task', 'capture.newEvent': 'New event', 'capture.details': 'Edit details', 'capture.quick': 'Quick entry', 'capture.todo': 'Task', 'capture.event': 'Event', 'capture.title': 'Title', 'capture.more': 'More options', 'capture.less': 'Fewer options', 'capture.moreA11y': 'Show more options', 'capture.lessA11y': 'Show fewer options',
  'capture.for': '👤 For', 'capture.forWhom': 'For whom?', 'capture.repeat': '🔄 Repeat', 'capture.on': 'On', 'capture.off': 'Off', 'capture.daily': 'Every day', 'capture.weekdays': 'Weekdays (Mon–Fri)', 'capture.seriesEnd': 'Series end', 'capture.endsOn': 'Ends on', 'capture.noEnd': 'No end date', 'capture.addEndDate': 'Add end date', 'capture.period': 'Time period', 'capture.location': 'Location', 'capture.locationOptional': 'Location (optional)', 'capture.reminder': 'Reminder', 'capture.time': '🕒 Time', 'capture.due': 'Due', 'capture.timeRequired': 'Time required', 'capture.noDate': 'Do not set a date', 'capture.addDate': 'Add date', 'capture.notes': '📝 Notes', 'capture.notesPlain': 'Notes', 'capture.detailsPlaceholder': 'Add details …', 'capture.deleteEntry': '🗑️ Delete entry',
  'capture.clock': '🕒 Time', 'capture.withTime': 'With time', 'capture.from': 'From', 'capture.to': 'To', 'capture.start': 'Start', 'capture.end': 'End', 'capture.removeEnd': 'Remove end time', 'capture.addEnd': 'Add end time', 'capture.applyPeriod': 'Apply time period', 'capture.choose': 'Choose {{label}}', 'capture.fromTime': 'from {{time}}',
  'reminder.none': 'No reminder', 'reminder.atStart': 'At start', 'reminder.oneHour': '1 hour before', 'reminder.twoHours': '2 hours before', 'reminder.oneDay': '1 day before', 'reminder.minutes': '{{count}} min before',

  'capture.color': '🎨 Colour', 'capture.colorAuto': 'Automatic', 'capture.colorAutoHint': 'Colour of the person', 'color.rose': 'Rose', 'color.coral': 'Coral', 'color.amber': 'Amber', 'color.olive': 'Olive', 'color.green': 'Green', 'color.teal': 'Teal', 'color.blue': 'Blue', 'color.indigo': 'Violet', 'color.berry': 'Berry', 'color.slate': 'Slate',
  'capture.weekdaysMissingTitle': 'Weekdays missing', 'capture.weekdaysMissingBody': 'Choose at least one weekday.', 'capture.invalidStart': 'Choose a valid start time.', 'capture.invalidEnd': 'Choose a valid end time.', 'capture.invalidTime': 'Choose a valid time.', 'capture.timeMissingTitle': 'Time missing', 'capture.timeMissingBody': 'Recurring tasks need a time or due date.', 'capture.recurringMultiDay': 'Recurring events can only take place within one day in this version.', 'capture.invalidEndDateTitle': 'Invalid end date', 'capture.invalidEndDateBody': 'The end date cannot be before the first event in the series.', 'capture.changeEndTitle': 'Change end date', 'capture.changeEndBody': 'The end date always applies to the entire series.', 'capture.entireSeries': 'Entire series', 'capture.saveChangesTitle': 'Save changes', 'capture.saveChangesBody': 'Apply this change only to this day or to the entire series?', 'capture.onlyDay': 'This day only', 'capture.deleteRecurringBody': 'Delete only this day or the entire series?', 'capture.deleteTitle': 'Delete entry', 'capture.deleteMetadataBody': 'The series metadata could not be read. Do you really want to delete this entry?', 'capture.deleteBody': 'Do you really want to delete this entry?',
  'widget.timelineTitle': 'Planner', 'widget.tasksTitle': 'Tasks', 'widget.open': 'open', 'widget.done': 'done', 'widget.flexible': 'Flexible', 'widget.allDay': 'All day', 'widget.now': 'Now', 'widget.noEventsTitle': 'No events', 'widget.noEventsHint': 'Nothing planned today', 'widget.noMoreEvents': 'No more events today', 'widget.noTasksTitle': 'All done', 'widget.noTasksHint': 'No open tasks', 'widget.moreItems': '+{{count}} more', 'widget.eventsCount': '{{count}} events', 'widget.signedOut': 'Open in Lotti Baby', 'widget.staleHint': 'Open the app to refresh', 'widget.addTask': 'Task',
};
const es: Catalog = {
  'common.error': 'Error', 'common.cancel': 'Cancelar', 'common.save': 'Guardar', 'common.delete': 'Eliminar', 'common.today': 'Hoy', 'common.tomorrow': 'Mañana', 'common.yesterday': 'Ayer', 'common.allDay': 'Todo el día', 'common.open': 'Abierto', 'dayPart.morning': 'Mañana', 'dayPart.midday': 'Mediodía', 'dayPart.afternoon': 'Tarde', 'dayPart.evening': 'Noche', 'person.me': 'Yo', 'person.baby': 'Bebé', 'person.partner': 'Pareja', 'person.child': 'Niño', 'person.family': 'Familia',
  'view.day': 'Día', 'view.week': 'Semana', 'view.month': 'Mes', 'view.dayOverview': 'Vista diaria', 'view.weekOverview': 'Vista semanal', 'view.monthOverview': 'Vista mensual', 'greeting.hello': 'Hola', 'greeting.welcome': 'Qué bien que estés aquí.', 'greeting.morning': 'Buenos días', 'greeting.morningSub': '¿Preparada para un nuevo día?', 'greeting.day': 'Hola', 'greeting.daySub': '¿Qué queda por hacer hoy?', 'greeting.evening': 'Buenas tardes', 'greeting.eveningSub': 'Termina el día con calma.', 'greeting.night': 'Buenas noches', 'greeting.nightSub': 'Es hora de desconectar y descansar.', 'greeting.you': 'tú',
  'sync.loadFailed': 'No se pudo cargar la sincronización del calendario.', 'sync.changes': '{{count}} cambios sincronizados', 'sync.current': 'Todo está actualizado', 'sync.failed': 'La sincronización del calendario ha fallado.', 'sync.enableFailed': 'No se pudo activar la sincronización.', 'sync.disableFailed': 'No se pudo desactivar la sincronización.', 'sync.settingsAccessibility': 'Ajustes de sincronización con Apple Calendar', 'sync.title': 'Apple Calendar', 'sync.ready': 'Lotti Baby · listo', 'sync.last': 'Lotti Baby · última sincronización {{time}}', 'sync.off': 'La sincronización está desactivada', 'sync.readyAction': 'Listo para sincronizar', 'sync.actionAccessibility': 'Sincronizar ahora con Apple Calendar',
  'delete.recurringTitle': 'Eliminar entrada recurrente', 'delete.recurringQuestion': '¿Eliminar solo este día o toda la serie?', 'delete.onlyDay': 'Eliminar solo este día', 'delete.series': 'Eliminar todas las repeticiones', 'delete.failed': 'No se pudo eliminar la entrada.', 'delete.unexpected': 'Se ha producido un error.', 'validation.timeTitle': 'Hora no válida', 'validation.timeMessage': 'La cita no tiene una hora de inicio válida.', 'validation.unsupportedTitle': 'No compatible', 'validation.unsupportedMessage': 'No se puede cambiar el tipo de un solo día de la serie.',
  'navigation.previousDay': 'Día anterior', 'navigation.previousWeek': 'Semana anterior', 'navigation.previousMonth': 'Mes anterior', 'navigation.nextDay': 'Día siguiente', 'navigation.nextWeek': 'Semana siguiente', 'navigation.nextMonth': 'Mes siguiente', 'tasks.title': 'Tareas', 'tasks.open': '{{count}} abiertas', 'tasks.flexible': 'Flexible', 'tasks.flexibleWith': 'Flexible · {{name}}', 'tasks.empty': 'No hay tareas abiertas sin fecha', 'tasks.hideDone': 'Ocultar tareas completadas', 'tasks.showDone': 'Mostrar tareas completadas', 'tasks.done': 'Completadas', 'calendar.week': 'Plan semanal', 'calendar.month': 'Calendario mensual', 'weekday.mon': 'Lu', 'weekday.tue': 'Ma', 'weekday.wed': 'Mi', 'weekday.thu': 'Ju', 'weekday.fri': 'Vi', 'weekday.sat': 'Sá', 'weekday.sun': 'Do',
  'capture.editTodo': 'Editar tarea', 'capture.editEvent': 'Editar evento', 'capture.newTodo': 'Nueva tarea', 'capture.newEvent': 'Nuevo evento', 'capture.details': 'Editar detalles', 'capture.quick': 'Entrada rápida', 'capture.todo': 'Tarea', 'capture.event': 'Evento', 'capture.title': 'Título', 'capture.more': 'Más opciones', 'capture.less': 'Menos opciones', 'capture.moreA11y': 'Mostrar más opciones', 'capture.lessA11y': 'Mostrar menos opciones',
  'capture.for': '👤 Para', 'capture.forWhom': '¿Para quién?', 'capture.repeat': '🔄 Repetir', 'capture.on': 'Sí', 'capture.off': 'No', 'capture.daily': 'Cada día', 'capture.weekdays': 'Entre semana (lu–vi)', 'capture.seriesEnd': 'Fin de la serie', 'capture.endsOn': 'Termina el', 'capture.noEnd': 'Sin fecha de fin', 'capture.addEndDate': 'Añadir fecha de fin', 'capture.period': 'Periodo', 'capture.location': 'Lugar', 'capture.locationOptional': 'Lugar (opcional)', 'capture.reminder': 'Recordatorio', 'capture.time': '🕒 Momento', 'capture.due': 'Vence', 'capture.timeRequired': 'Hora obligatoria', 'capture.noDate': 'No establecer fecha', 'capture.addDate': 'Añadir fecha', 'capture.notes': '📝 Notas', 'capture.notesPlain': 'Notas', 'capture.detailsPlaceholder': 'Añadir detalles …', 'capture.deleteEntry': '🗑️ Eliminar entrada',
  'capture.clock': '🕒 Hora', 'capture.withTime': 'Con hora', 'capture.from': 'Desde', 'capture.to': 'Hasta', 'capture.start': 'Inicio', 'capture.end': 'Fin', 'capture.removeEnd': 'Quitar hora de fin', 'capture.addEnd': 'Añadir hora de fin', 'capture.applyPeriod': 'Aplicar periodo', 'capture.choose': 'Elegir {{label}}', 'capture.fromTime': 'desde {{time}}',
  'reminder.none': 'Sin recordatorio', 'reminder.atStart': 'Al empezar', 'reminder.oneHour': '1 hora antes', 'reminder.twoHours': '2 horas antes', 'reminder.oneDay': '1 día antes', 'reminder.minutes': '{{count}} min antes',

  'capture.color': '🎨 Color', 'capture.colorAuto': 'Automático', 'capture.colorAutoHint': 'Color de la persona', 'color.rose': 'Rosa', 'color.coral': 'Coral', 'color.amber': 'Ámbar', 'color.olive': 'Oliva', 'color.green': 'Verde', 'color.teal': 'Turquesa', 'color.blue': 'Azul', 'color.indigo': 'Violeta', 'color.berry': 'Baya', 'color.slate': 'Pizarra',
  'capture.weekdaysMissingTitle': 'Faltan días', 'capture.weekdaysMissingBody': 'Elige al menos un día de la semana.', 'capture.invalidStart': 'Elige una hora de inicio válida.', 'capture.invalidEnd': 'Elige una hora de fin válida.', 'capture.invalidTime': 'Elige una hora válida.', 'capture.timeMissingTitle': 'Falta la hora', 'capture.timeMissingBody': 'Las tareas recurrentes necesitan una hora o fecha de vencimiento.', 'capture.recurringMultiDay': 'En esta versión, los eventos recurrentes solo pueden celebrarse dentro del mismo día.', 'capture.invalidEndDateTitle': 'Fecha de fin no válida', 'capture.invalidEndDateBody': 'La fecha de fin no puede ser anterior al primer evento de la serie.', 'capture.changeEndTitle': 'Cambiar fecha de fin', 'capture.changeEndBody': 'La fecha de fin siempre se aplica a toda la serie.', 'capture.entireSeries': 'Toda la serie', 'capture.saveChangesTitle': 'Guardar cambios', 'capture.saveChangesBody': '¿Aplicar el cambio solo a este día o a toda la serie?', 'capture.onlyDay': 'Solo este día', 'capture.deleteRecurringBody': '¿Eliminar solo este día o toda la serie?', 'capture.deleteTitle': 'Eliminar entrada', 'capture.deleteMetadataBody': 'No se pudieron leer los metadatos de la serie. ¿Seguro que quieres eliminar esta entrada?', 'capture.deleteBody': '¿Seguro que quieres eliminar esta entrada?',
  'widget.timelineTitle': 'Planificador', 'widget.tasksTitle': 'Tareas', 'widget.open': 'abiertas', 'widget.done': 'hechas', 'widget.flexible': 'Flexible', 'widget.allDay': 'Todo el día', 'widget.now': 'Ahora', 'widget.noEventsTitle': 'Sin eventos', 'widget.noEventsHint': 'Hoy no hay nada planeado', 'widget.noMoreEvents': 'No hay más eventos hoy', 'widget.noTasksTitle': 'Todo hecho', 'widget.noTasksHint': 'No hay tareas abiertas', 'widget.moreItems': '+{{count}} más', 'widget.eventsCount': '{{count}} eventos', 'widget.signedOut': 'Abrir en Lotti Baby', 'widget.staleHint': 'Abre la app para actualizar', 'widget.addTask': 'Tarea',
};
export const PLANNER_TRANSLATIONS: Record<PlannerLocale, Catalog> = { de, en, es };
export const getPlannerLocaleTag = (locale: PlannerLocale) => ({ de: 'de-DE', en: 'en-US', es: 'es-ES' })[locale];
export const translatePlannerText = (locale: PlannerLocale, key: PlannerTranslationKey, params: Record<string, string | number> = {}) => {
  const template = PLANNER_TRANSLATIONS[locale]?.[key] ?? de[key] ?? key;
  return template.replace(/\{\{(\w+)\}\}/g, (_, token: string) => String(params[token] ?? `{{${token}}}`));
};
