/** Translation boundary for the pregnancy home screen. */
export type PregnancyHomeLocale = 'de' | 'en' | 'es';
export const DEFAULT_PREGNANCY_HOME_LOCALE: PregnancyHomeLocale = 'de';

const de = {
  'common.error': 'Fehler', 'common.notice': 'Hinweis', 'common.ok': 'OK',
  'card.countdown.title': 'Countdown', 'card.countdown.description': 'Dein Weg zur Geburt', 'card.contractions.title': 'Wehen-Tracker', 'card.contractions.description': 'Wehen messen und verfolgen', 'card.planner.title': 'Planer', 'card.planner.description': 'Tagesplanung & Termine', 'card.checklist.title': 'Checkliste', 'card.checklist.description': 'Kliniktasche vorbereiten', 'card.birthPlan.title': 'Geburtsplan', 'card.birthPlan.description': 'Wünsche für die Geburt', 'card.selfcare.title': 'Mama Selfcare', 'card.selfcare.description': 'Nimm dir Zeit für dich', 'card.questions.title': 'Meine Fragen', 'card.questions.description': 'Fragen für den nächsten Termin', 'card.baby.title': 'Mein Baby', 'card.baby.description': 'Infos anpassen & Entwicklung sehen', 'card.names.title': 'Babynamen', 'card.names.description': 'Finde den perfekten Namen', 'card.weight.title': 'Gewichtskurve', 'card.weight.description': 'Gewicht tracken',
  'alert.keepTile': 'Mindestens eine Schnellzugriff-Kachel muss sichtbar bleiben.', 'dueDate.overdueTitle': 'Entbindungstermin überschritten', 'dueDate.overdueQuestion': 'Dein Entbindungstermin ist bereits überschritten. Ist dein Baby schon geboren?', 'dueDate.notBorn': 'Noch nicht geboren', 'dueDate.born': 'Ja, mein Baby ist da!', 'born.congratulations': 'Herzlichen Glückwunsch!', 'born.message': 'Wir freuen uns mit dir über die Geburt deines Babys! 🎉{{syncMessage}}', 'born.synced': '\n\nDiese Information wurde auch mit {{names}} geteilt.', 'born.statusFailed': 'Es gab ein Problem bei der Aktualisierung des Status.',
  'refresh.updated': 'Daten aktualisiert', 'refresh.active': 'Aktualisiere …', 'refresh.pull': 'Zum Aktualisieren ziehen', 'overview.title': 'Dein Tag im Überblick', 'overview.week': 'SSW', 'overview.trimester': 'Trimester', 'overview.progress': 'Fortschritt',
  'shop.button': 'Shop', 'shop.accessibility': 'Lotti Baby Shop öffnen', 'shop.eyebrow': 'Lotti Baby Shop', 'shop.title': 'Prints zum Aufbügeln', 'shop.description': 'Lieblingsmotiv wählen und direkt bestellen', 'shop.empty': 'Prints ansehen und bestellen.',
  'quick.hideAccessibility': '{{title}} ausblenden', 'quick.hiddenTitle': 'Ausgeblendet', 'quick.hidden.one': '1 Kachel ist ausgeblendet.', 'quick.hidden.other': '{{count}} Kacheln sind ausgeblendet.', 'quick.restoreAll': 'Alle einblenden', 'quick.restoreHint': 'Tippe auf eine ausgeblendete Kachel, um sie wieder anzuzeigen.', 'quick.restore': 'Einblenden', 'quick.title': 'Schnellzugriff', 'quick.done': 'Fertig', 'quick.editHint': 'Kacheln verschieben, ausblenden und mit „Fertig“ speichern.', 'quick.longPressHint': 'Lange auf eine Kachel drücken, um die Reihenfolge anzupassen.', 'quick.hiddenHint': 'Ausgeblendete Kacheln kannst du unten wieder einblenden.',
  'greeting.fallbackName': 'Mama', 'greeting.hello': 'Hallo {{name}}!', 'birthPrep.title': 'Geburtsvorbereitung', 'birthPrep.description': 'Ab SSW 34 findest du alle Maßnahmen übersichtlich im Countdown.', 'birthPrep.action': 'Zur Übersicht',
  'overdue.baby': 'Dein Baby ist jetzt vollständig entwickelt. Die Plazenta versorgt es weiterhin mit allen notwendigen Nährstoffen. Die Verbindung zwischen euch beiden ist stärker denn je. Das Immunsystem deines Babys wird durch die Übertragung von Antikörpern über die Plazenta weiter gestärkt.', 'overdue.mother': 'Viele Frauen empfinden diese Wartezeit als besonders anstrengend. Versuche dich abzulenken und nutze die Zeit für Entspannung. Bewegung kann helfen, den Geburtsprozess anzuregen. Achte auf Anzeichen für Wehen oder den Abgang des Mutterkuchens. Bei Unsicherheiten kontaktiere immer deine Hebamme oder deinen Arzt.', 'overdue.partner': 'Deine Unterstützung ist jetzt besonders wichtig. Sei geduldig und verständnisvoll. Hilf beim Ablenken und sorge für Aktivitäten, die die Wartezeit verkürzen. Stelle sicher, dass alles für die Fahrt ins Krankenhaus bereit ist und ihr jederzeit los könnt.',
  'overdue.symptom.hardBelly': 'Harter, tiefer Bauch', 'overdue.symptom.discharge': 'Verstärkter Ausfluss', 'overdue.symptom.pressure': 'Zunehmender Druck im Becken', 'overdue.symptom.contractions': 'Vorwehen (Übungswehen)', 'overdue.symptom.backPain': 'Rückenschmerzen', 'overdue.symptom.fatigue': 'Verstärkte Müdigkeit', 'overdue.symptom.tension': 'Emotionale Anspannung',
} as const;
export type PregnancyHomeTranslationKey = keyof typeof de;
type Catalog = Record<PregnancyHomeTranslationKey, string>;

const en: Catalog = {
  'common.error': 'Error', 'common.notice': 'Note', 'common.ok': 'OK',
  'card.countdown.title': 'Countdown', 'card.countdown.description': 'Your journey to birth', 'card.contractions.title': 'Contraction tracker', 'card.contractions.description': 'Time and track contractions', 'card.planner.title': 'Planner', 'card.planner.description': 'Daily plans & appointments', 'card.checklist.title': 'Checklist', 'card.checklist.description': 'Prepare your hospital bag', 'card.birthPlan.title': 'Birth plan', 'card.birthPlan.description': 'Your wishes for birth', 'card.selfcare.title': 'Mom self-care', 'card.selfcare.description': 'Take some time for yourself', 'card.questions.title': 'My questions', 'card.questions.description': 'Questions for your next appointment', 'card.baby.title': 'My baby', 'card.baby.description': 'Update information & view development', 'card.names.title': 'Baby names', 'card.names.description': 'Find the perfect name', 'card.weight.title': 'Weight chart', 'card.weight.description': 'Track weight',
  'alert.keepTile': 'At least one quick-access tile must remain visible.', 'dueDate.overdueTitle': 'Due date has passed', 'dueDate.overdueQuestion': 'Your due date has already passed. Has your baby been born?', 'dueDate.notBorn': 'Not born yet', 'dueDate.born': 'Yes, my baby is here!', 'born.congratulations': 'Congratulations!', 'born.message': 'We are so happy for you and the arrival of your baby! 🎉{{syncMessage}}', 'born.synced': '\n\nThis information was also shared with {{names}}.', 'born.statusFailed': 'There was a problem updating the status.',
  'refresh.updated': 'Data updated', 'refresh.active': 'Refreshing …', 'refresh.pull': 'Pull to refresh', 'overview.title': 'Your pregnancy at a glance', 'overview.week': 'WEEK', 'overview.trimester': 'Trimester', 'overview.progress': 'Progress',
  'shop.button': 'Shop', 'shop.accessibility': 'Open Lotti Baby Shop', 'shop.eyebrow': 'Lotti Baby Shop', 'shop.title': 'Iron-on prints', 'shop.description': 'Choose your favorite design and order it directly', 'shop.empty': 'Browse and order prints.',
  'quick.hideAccessibility': 'Hide {{title}}', 'quick.hiddenTitle': 'Hidden', 'quick.hidden.one': '1 tile is hidden.', 'quick.hidden.other': '{{count}} tiles are hidden.', 'quick.restoreAll': 'Show all', 'quick.restoreHint': 'Tap a hidden tile to show it again.', 'quick.restore': 'Show', 'quick.title': 'Quick access', 'quick.done': 'Done', 'quick.editHint': 'Move or hide tiles and tap “Done” to save.', 'quick.longPressHint': 'Press and hold a tile to change the order.', 'quick.hiddenHint': 'You can show hidden tiles again below.',
  'greeting.fallbackName': 'Mom', 'greeting.hello': 'Hello {{name}}!', 'birthPrep.title': 'Birth preparation', 'birthPrep.description': 'From week 34, you can find all steps clearly organized in the countdown.', 'birthPrep.action': 'View overview',
  'overdue.baby': 'Your baby is now fully developed. The placenta continues to provide every nutrient they need, and the bond between you is stronger than ever. Antibodies transferred through the placenta continue to strengthen your baby’s immune system.', 'overdue.mother': 'Many women find this waiting period especially tiring. Try to distract yourself and make time to relax. Gentle movement may help labor begin. Watch for contractions and other signs, and contact your maternity care team if you are unsure.', 'overdue.partner': 'Your support matters more than ever. Be patient and understanding, help provide distraction, and make sure everything is ready for the journey to hospital so you can leave at any time.',
  'overdue.symptom.hardBelly': 'Low, firm belly', 'overdue.symptom.discharge': 'Increased discharge', 'overdue.symptom.pressure': 'Increasing pelvic pressure', 'overdue.symptom.contractions': 'Practice contractions', 'overdue.symptom.backPain': 'Back pain', 'overdue.symptom.fatigue': 'Increased tiredness', 'overdue.symptom.tension': 'Emotional tension',
};

const es: Catalog = {
  'common.error': 'Error', 'common.notice': 'Aviso', 'common.ok': 'Aceptar',
  'card.countdown.title': 'Cuenta atrás', 'card.countdown.description': 'Tu camino hasta el parto', 'card.contractions.title': 'Seguimiento de contracciones', 'card.contractions.description': 'Mide y registra las contracciones', 'card.planner.title': 'Planificador', 'card.planner.description': 'Plan diario y citas', 'card.checklist.title': 'Lista de control', 'card.checklist.description': 'Preparar la bolsa del hospital', 'card.birthPlan.title': 'Plan de parto', 'card.birthPlan.description': 'Tus preferencias para el parto', 'card.selfcare.title': 'Autocuidado de mamá', 'card.selfcare.description': 'Dedícate tiempo', 'card.questions.title': 'Mis preguntas', 'card.questions.description': 'Preguntas para la próxima cita', 'card.baby.title': 'Mi bebé', 'card.baby.description': 'Actualizar datos y ver el desarrollo', 'card.names.title': 'Nombres para bebés', 'card.names.description': 'Encuentra el nombre perfecto', 'card.weight.title': 'Curva de peso', 'card.weight.description': 'Registrar el peso',
  'alert.keepTile': 'Debe quedar visible al menos un acceso rápido.', 'dueDate.overdueTitle': 'La fecha prevista ya ha pasado', 'dueDate.overdueQuestion': 'La fecha prevista de parto ya ha pasado. ¿Ha nacido tu bebé?', 'dueDate.notBorn': 'Todavía no', 'dueDate.born': '¡Sí, mi bebé ya está aquí!', 'born.congratulations': '¡Enhorabuena!', 'born.message': '¡Nos alegramos mucho contigo por el nacimiento de tu bebé! 🎉{{syncMessage}}', 'born.synced': '\n\nEsta información también se ha compartido con {{names}}.', 'born.statusFailed': 'Se ha producido un problema al actualizar el estado.',
  'refresh.updated': 'Datos actualizados', 'refresh.active': 'Actualizando …', 'refresh.pull': 'Desliza para actualizar', 'overview.title': 'Tu embarazo de un vistazo', 'overview.week': 'SEMANA', 'overview.trimester': 'Trimestre', 'overview.progress': 'Progreso',
  'shop.button': 'Tienda', 'shop.accessibility': 'Abrir la tienda Lotti Baby', 'shop.eyebrow': 'Tienda Lotti Baby', 'shop.title': 'Estampados termoadhesivos', 'shop.description': 'Elige tu diseño favorito y pídelo directamente', 'shop.empty': 'Ver y pedir estampados.',
  'quick.hideAccessibility': 'Ocultar {{title}}', 'quick.hiddenTitle': 'Ocultos', 'quick.hidden.one': 'Hay 1 acceso oculto.', 'quick.hidden.other': 'Hay {{count}} accesos ocultos.', 'quick.restoreAll': 'Mostrar todos', 'quick.restoreHint': 'Toca un acceso oculto para volver a mostrarlo.', 'quick.restore': 'Mostrar', 'quick.title': 'Acceso rápido', 'quick.done': 'Listo', 'quick.editHint': 'Mueve u oculta accesos y pulsa «Listo» para guardar.', 'quick.longPressHint': 'Mantén pulsado un acceso para cambiar el orden.', 'quick.hiddenHint': 'Puedes volver a mostrar abajo los accesos ocultos.',
  'greeting.fallbackName': 'Mamá', 'greeting.hello': '¡Hola, {{name}}!', 'birthPrep.title': 'Preparación al parto', 'birthPrep.description': 'A partir de la semana 34 encontrarás todas las medidas organizadas en la cuenta atrás.', 'birthPrep.action': 'Ver resumen',
  'overdue.baby': 'Tu bebé ya está completamente desarrollado. La placenta sigue aportándole todos los nutrientes necesarios y vuestro vínculo es más fuerte que nunca. Los anticuerpos que recibe a través de la placenta continúan reforzando su sistema inmunitario.', 'overdue.mother': 'Muchas mujeres sienten que esta espera resulta especialmente agotadora. Intenta distraerte y aprovecha para descansar. El movimiento suave puede ayudar a iniciar el parto. Si tienes dudas, consulta siempre a tu matrona o equipo médico.', 'overdue.partner': 'Tu apoyo es ahora especialmente importante. Ten paciencia, muestra comprensión y asegúrate de que todo esté listo para ir al hospital en cualquier momento.',
  'overdue.symptom.hardBelly': 'Vientre bajo y duro', 'overdue.symptom.discharge': 'Aumento del flujo', 'overdue.symptom.pressure': 'Mayor presión pélvica', 'overdue.symptom.contractions': 'Contracciones de práctica', 'overdue.symptom.backPain': 'Dolor de espalda', 'overdue.symptom.fatigue': 'Mayor cansancio', 'overdue.symptom.tension': 'Tensión emocional',
};

export const PREGNANCY_HOME_TRANSLATIONS: Record<PregnancyHomeLocale, Catalog> = { de, en, es };
export const getPregnancyHomeLocaleTag = (locale: PregnancyHomeLocale) => ({ de: 'de-DE', en: 'en-US', es: 'es-ES' })[locale];
export const translatePregnancyHomeText = (locale: PregnancyHomeLocale, key: PregnancyHomeTranslationKey, params: Record<string, string | number> = {}) => {
  const template = PREGNANCY_HOME_TRANSLATIONS[locale]?.[key] ?? de[key] ?? key;
  return template.replace(/\{\{(\w+)\}\}/g, (_, token: string) => String(params[token] ?? `{{${token}}}`));
};
