import type { AppLocale } from '@/lib/localization';
import type { AdvisorAnalysis, AdvisorInsight, DailySignals } from './types';
import type { AdvisorHistoryItem } from './advisorStorage';

const ui = {
  de: {
    sleep: 'Schlaf', feeding: 'Ernährung', diaper: 'Windeln', weather: 'Wetter', motivation: 'Motivation', daily: 'Täglich', importantOnly: 'Nur Wichtiges', off: 'Aus', today: 'Heute', yesterday: 'Gestern',
    notificationTitle: 'Mitteilungen nicht möglich', notificationMessage: 'Bitte erlaube Lotti Benachrichtigungen in den Systemeinstellungen. Ohne Erlaubnis kann Lotti dir keine Tageshinweise schicken.', shareTitle: 'Übergabe für Lotti', shareFailedTitle: 'Teilen nicht möglich', shareFailedMessage: 'Die Übergabe konnte gerade nicht geöffnet werden.',
    briefing: 'Tagesbriefing', todayByLotti: 'Heute · von Lotti', discovered: '✨ Heute entdeckt', combined: 'Lotti hat Schlaf, Ernährung und Wetter zusammengeführt.', why: 'Warum?', details: 'Details', limitMode: '🫶 Am-Limit-Modus', shortNight: '🌙 Kurze Nacht erkannt', rhythm: '✨ Aus eurem Rhythmus',
    limitText: 'Lotti hat den aktuellen Stand schon in eine konkrete Übergabe gepackt. Du musst nichts erklären oder zusätzlich dokumentieren.', now: 'Jetzt', next: 'Als Nächstes', yourWindow: 'Dein Fenster', normalOverview: 'Normalen Überblick anzeigen', atLimit: 'Ich bin am Limit', limitHint: 'Alles ausblenden und sofort Ablösung anfragen',
    copilot: 'Dein Eltern-Copilot', copilotHint: 'Lotti ordnet Babys Tag ein und sagt dir, was jetzt wichtig ist.', example: 'Beispiel', previous: 'Frühere Hinweise', more: 'Weitere Hinweise', settings: 'Einstellungen', topics: 'Themen', notifications: 'Mitteilungen', push: 'Push für wichtige Hinweise', pushHint: 'Max. 1 Nachricht am Tag, morgens gegen 8 Uhr – nie in deinen stillen Zeiten ({{start}}–{{end}} Uhr).', frequency: 'Häufigkeit',
    timelineTitle: 'Euer weiterer Tag', timelineHint: 'Persönliche Prognosen und Planer-Termine bis heute Abend', timelineOpenPlanner: 'Planer öffnen', timelineEmpty: 'Für heute stehen keine weiteren Termine oder belastbaren Prognosen an.', timelinePrediction: 'Prognose', timelineNow: 'Jetzt', timelineSleep: 'Voraussichtliches Schlaffenster', timelineFeeding: 'Voraussichtliche Mahlzeit', timelineCurrentSleep: 'Schlaf läuft', timelineBasedOn: 'Aus {{count}} persönlichen Abständen abgeleitet', timelineConflict: 'Kann sich mit „{{title}}“ überschneiden', timelineAllDay: 'Ganztägig', timelineToday: 'Heute',
    privacyTitle: '🛡️ Deine Daten', privacyText: 'Wenn du den Am-Limit-Modus aktivierst, wird diese Auswahl in deinem Konto gespeichert, aber nicht an den KI-Dienst übertragen. Für den Wetterteil wird dein ungefährer Standort (auf ca. 1 km gerundet) gespeichert und an Open-Meteo übertragen – nie deine genaue Position. Für die persönliche Formulierung gehen die Tageswerte (Schlaf, Mahlzeiten, Windeln, Wetter) sowie Vorname und Alter deines Babys an einen KI-Dienst. Alles lässt sich hier jederzeit abschalten.', privacyLink: 'Mehr in der Datenschutzerklärung',
    title: 'Lottis Fürsorge', subtitle: 'Eine Sache weniger im Kopf', locked: 'Noch nicht freigeschaltet', lockedText: 'Lottis Fürsorge ist aktuell in Erprobung und nur für Premiumtester verfügbar. Bald öffnen wir das Feature für Premium-Mitglieder.', disclaimer: 'Lottis Hinweise sind allgemeine Alltagstipps und ersetzen keinen medizinischen Rat, keine Diagnose und keine Behandlung. Bei Fieber, Trinkverweigerung, Teilnahmslosigkeit oder wenn du dir unsicher bist: wende dich an deine Hebamme, Kinderarztpraxis oder den ärztlichen Bereitschaftsdienst (116 117), im Notfall an den Notruf 112.',
    week: 'Woche', month: 'Monat', year: 'Jahr', meals: 'Mahlzeiten', analyticsTitle: 'Rhythmus & Berichte', analyticsHint: 'Zeiträume vergleichen und Muster gemeinsam betrachten', days: 'Tage', reportLoading: 'Bericht wird aus euren Einträgen aufgebaut …', dataUnavailable: 'Daten gerade nicht erreichbar', dataUnavailableText: 'Der Tagesbereich funktioniert weiter. Der Bericht versucht es beim nächsten Öffnen erneut.', reportGrowing: 'Der Bericht wächst mit euren Einträgen', reportGrowingText: 'Sobald Schlaf, Mahlzeiten oder Windeln erfasst sind, erscheinen hier Vergleiche und Kurven.', comparisonLearning: 'Vergleich lernt noch', stable: 'nahezu stabil', change: '{{arrow}} {{percent}} % zum Vergleich', averageDays: 'Ø aus {{count}} erfassten Tagen', trend: 'Verlauf', trendHint: 'Durchgezogen aktuell · gestrichelt {{comparison}}', noticeable: 'Was auffällt', together: 'Zusammen betrachtet', method: 'Durchschnitte beziehen sich auf Tage mit einem passenden Eintrag. Zusammenhänge zeigen gemeinsame Bewegungen, keine medizinische Bewertung oder Ursache.', chartHistory: '{{metric}}-Verlauf',
  },
  en: {
    sleep: 'Sleep', feeding: 'Feeding', diaper: 'Diapers', weather: 'Weather', motivation: 'Motivation', daily: 'Daily', importantOnly: 'Important only', off: 'Off', today: 'Today', yesterday: 'Yesterday',
    notificationTitle: 'Notifications unavailable', notificationMessage: 'Allow Lotti notifications in your system settings. Without permission, Lotti cannot send daily insights.', shareTitle: 'Lotti care handoff', shareFailedTitle: 'Could not share', shareFailedMessage: 'The handoff could not be opened right now.',
    briefing: 'Daily briefing', todayByLotti: 'Today · from Lotti', discovered: '✨ Spotted today', combined: 'Lotti combined sleep, feeding, and weather.', why: 'Why?', details: 'Details', limitMode: '🫶 At-my-limit mode', shortNight: '🌙 Short night detected', rhythm: '✨ Based on your rhythm',
    limitText: 'Lotti has already turned the current status into a specific handoff. You do not need to explain or document anything else.', now: 'Now', next: 'Up next', yourWindow: 'Your window', normalOverview: 'Show normal overview', atLimit: "I'm at my limit", limitHint: 'Hide everything and ask for relief now',
    copilot: 'Your parenting copilot', copilotHint: "Lotti puts your baby's day into context and tells you what matters now.", example: 'Example', previous: 'Previous insights', more: 'More insights', settings: 'Settings', topics: 'Topics', notifications: 'Notifications', push: 'Push important insights', pushHint: 'No more than 1 message a day, around 8 a.m. – never during your quiet hours ({{start}}–{{end}}).', frequency: 'Frequency',
    timelineTitle: 'The rest of your day', timelineHint: 'Personal predictions and planner events through this evening', timelineOpenPlanner: 'Open planner', timelineEmpty: 'There are no more events or reliable predictions for today.', timelinePrediction: 'Prediction', timelineNow: 'Now', timelineSleep: 'Expected sleep window', timelineFeeding: 'Expected feed', timelineCurrentSleep: 'Sleep in progress', timelineBasedOn: 'Based on {{count}} personal intervals', timelineConflict: 'May overlap with “{{title}}”', timelineAllDay: 'All day', timelineToday: 'Today',
    privacyTitle: '🛡️ Your data', privacyText: "When you enable at-my-limit mode, the selection is saved to your account but is not sent to the AI service. For weather, your approximate location (rounded to about 1 km) is saved and sent to Open-Meteo – never your precise location. Daily values (sleep, feeds, diapers, weather), plus your baby's first name and age, are sent to an AI service for personalized wording. You can turn all of this off here at any time.", privacyLink: 'Read more in the privacy policy',
    title: "Lotti's Care", subtitle: 'One less thing on your mind', locked: 'Not available yet', lockedText: "Lotti's Care is currently being tested and is only available to premium testers. We will open the feature to Premium members soon.", disclaimer: "Lotti's insights are general everyday tips and do not replace medical advice, diagnosis, or treatment. If your baby has a fever, refuses feeds, seems listless, or you are unsure, contact your midwife, pediatric practice, or local medical service; call your local emergency number in an emergency.",
    week: 'Week', month: 'Month', year: 'Year', meals: 'Feeds', analyticsTitle: 'Rhythm & reports', analyticsHint: 'Compare periods and explore patterns together', days: 'days', reportLoading: 'Building your report from your entries …', dataUnavailable: 'Data currently unavailable', dataUnavailableText: 'The daily section still works. The report will try again when you next open it.', reportGrowing: 'Your report grows with your entries', reportGrowingText: 'Once sleep, feeds, or diapers are recorded, comparisons and charts will appear here.', comparisonLearning: 'Still learning the comparison', stable: 'almost stable', change: '{{arrow}} {{percent}}% vs. comparison', averageDays: 'Average from {{count}} recorded days', trend: 'Trend', trendHint: 'Solid: current · dashed: {{comparison}}', noticeable: 'What stands out', together: 'Viewed together', method: 'Averages use days with a matching entry. Relationships show values moving together, not a medical assessment or a cause.', chartHistory: '{{metric}} trend',
  },
  es: {
    sleep: 'Sueño', feeding: 'Alimentación', diaper: 'Pañales', weather: 'Tiempo', motivation: 'Motivación', daily: 'A diario', importantOnly: 'Solo lo importante', off: 'Desactivado', today: 'Hoy', yesterday: 'Ayer',
    notificationTitle: 'Notificaciones no disponibles', notificationMessage: 'Permite las notificaciones de Lotti en los ajustes del sistema. Sin permiso, Lotti no puede enviarte consejos diarios.', shareTitle: 'Relevo de cuidados de Lotti', shareFailedTitle: 'No se pudo compartir', shareFailedMessage: 'No se pudo abrir el relevo en este momento.',
    briefing: 'Resumen diario', todayByLotti: 'Hoy · de Lotti', discovered: '✨ Detectado hoy', combined: 'Lotti ha combinado sueño, alimentación y tiempo.', why: '¿Por qué?', details: 'Detalles', limitMode: '🫶 Modo al límite', shortNight: '🌙 Noche corta detectada', rhythm: '✨ Según vuestro ritmo',
    limitText: 'Lotti ya ha preparado un relevo concreto con la situación actual. No tienes que explicar ni documentar nada más.', now: 'Ahora', next: 'A continuación', yourWindow: 'Tu margen', normalOverview: 'Mostrar resumen normal', atLimit: 'Estoy al límite', limitHint: 'Ocultar todo y pedir relevo ahora',
    copilot: 'Tu copiloto de crianza', copilotHint: 'Lotti interpreta el día de tu bebé y te dice qué importa ahora.', example: 'Ejemplo', previous: 'Consejos anteriores', more: 'Más consejos', settings: 'Ajustes', topics: 'Temas', notifications: 'Notificaciones', push: 'Avisos importantes por push', pushHint: 'Como máximo 1 mensaje al día, hacia las 8:00, nunca durante tus horas de silencio ({{start}}–{{end}}).', frequency: 'Frecuencia',
    timelineTitle: 'Lo que queda del día', timelineHint: 'Previsiones personales y citas de la agenda hasta esta noche', timelineOpenPlanner: 'Abrir agenda', timelineEmpty: 'No quedan citas ni previsiones fiables para hoy.', timelinePrediction: 'Previsión', timelineNow: 'Ahora', timelineSleep: 'Próximo margen de sueño', timelineFeeding: 'Próxima toma prevista', timelineCurrentSleep: 'Sueño en curso', timelineBasedOn: 'Basado en {{count}} intervalos personales', timelineConflict: 'Puede coincidir con «{{title}}»', timelineAllDay: 'Todo el día', timelineToday: 'Hoy',
    privacyTitle: '🛡️ Tus datos', privacyText: 'Al activar el modo al límite, esta elección se guarda en tu cuenta, pero no se envía al servicio de IA. Para el tiempo se guarda tu ubicación aproximada (redondeada a unos 1 km) y se envía a Open-Meteo, nunca tu posición exacta. Para personalizar el texto, se envían a un servicio de IA los valores diarios (sueño, comidas, pañales y tiempo), además del nombre y la edad de tu bebé. Puedes desactivarlo todo aquí cuando quieras.', privacyLink: 'Más información en la política de privacidad',
    title: 'Cuidados de Lotti', subtitle: 'Una cosa menos en la cabeza', locked: 'Aún no disponible', lockedText: 'Cuidados de Lotti está en fase de prueba y solo está disponible para usuarios de prueba Premium. Pronto abriremos la función a los miembros Premium.', disclaimer: 'Los consejos de Lotti son recomendaciones generales para el día a día y no sustituyen el consejo, diagnóstico ni tratamiento médico. Si tu bebé tiene fiebre, rechaza las tomas, está apático o tienes dudas, contacta con tu matrona, pediatra o servicio médico local; llama al número de emergencias de tu país en caso de urgencia.',
    week: 'Semana', month: 'Mes', year: 'Año', meals: 'Tomas', analyticsTitle: 'Ritmo e informes', analyticsHint: 'Compara periodos y observa patrones en conjunto', days: 'días', reportLoading: 'Creando el informe a partir de vuestros registros …', dataUnavailable: 'Datos no disponibles ahora', dataUnavailableText: 'La sección diaria sigue funcionando. El informe volverá a intentarlo la próxima vez que lo abras.', reportGrowing: 'El informe crece con vuestros registros', reportGrowingText: 'Cuando haya registros de sueño, tomas o pañales, aparecerán comparaciones y gráficas.', comparisonLearning: 'Aún aprendiendo la comparación', stable: 'casi estable', change: '{{arrow}} {{percent}} % frente a la comparación', averageDays: 'Media de {{count}} días registrados', trend: 'Evolución', trendHint: 'Línea continua: actual · discontinua: {{comparison}}', noticeable: 'Lo que destaca', together: 'Visto en conjunto', method: 'Las medias se basan en días con un registro correspondiente. Las relaciones muestran movimientos conjuntos, no una valoración médica ni una causa.', chartHistory: 'Evolución de {{metric}}',
  },
} as const;

export type AdvisorTranslationKey = keyof typeof ui.de;
export const translateAdvisor = (locale: AppLocale, key: AdvisorTranslationKey, params?: Record<string, string | number>) => {
  let value: string = ui[locale][key] ?? ui.de[key];
  for (const [name, replacement] of Object.entries(params ?? {})) value = value.replaceAll(`{{${name}}}`, String(replacement));
  return value;
};

const duration = (minutes: number, locale: AppLocale) => {
  const rounded = Math.round(minutes); const hours = Math.floor(rounded / 60); const rest = rounded % 60;
  if (locale === 'de') return hours ? `${hours} Std${rest ? ` ${rest} Min` : ''}` : `${rest} Min`;
  if (locale === 'es') return hours ? `${hours} h${rest ? ` ${rest} min` : ''}` : `${rest} min`;
  return hours ? `${hours} hr${rest ? ` ${rest} min` : ''}` : `${rest} min`;
};

const localizedInsight = (locale: AppLocale, id: string, signals: DailySignals): AdvisorInsight => {
  const n = signals.babyName; const temp = signals.weather.temperature ?? '–'; const rain = Math.round(signals.weather.rainProbability ?? 0);
  const values: Record<Exclude<AppLocale, 'de'>, Record<string, [string, string, string]>> = {
    en: {
      hot_low_feeding: ['Important today', 'Offer feeds more often today', `${n} has had a little less to drink than usual so far, and it will be warm. Feel free to offer breast or bottle more often; on hot days an extra sip can help.`],
      hot_low_sleep: ['Important today', 'Keep the next sleep cool and calm', `${n} has slept a little less today, and it will be muggy. Heat can disturb baby sleep – a cool, quiet room for the next sleep may help you both.`],
      hot: ['Important today', 'Protect from sun and heat', `It will be warm today. Keep ${n} out of direct sun, choose light clothing, and offer feeds a little more often.`],
      high_uv: ['Important today', 'Remember sun protection today', `The UV index will reach ${signals.weather.uvIndex ?? '–'} today. Shade, a sun hat, and light long clothing protect ${n} best; avoid midday sun.`],
      cold: ['Important today', 'Add a warm layer and hat', `It will be chilly today. An extra layer and a hat will help keep ${n} comfortably warm.`],
      low_sleep: ['Important today', 'Plan the next sleep a little earlier', `${n} has slept a little less than usual today. Consider an earlier next sleep – and take a short break yourself if you can.`],
      rain_likely: ['Good to know today', 'Plan for rain today', `The forecast shows a ${rain}% chance of rain. Pack the stroller rain cover or enjoy a cozy day indoors.`],
      low_feeding: ['Important today', 'It may be time to offer another feed', `${n} has had ${signals.feeding.totalCount} feeds so far. Based on your usual rhythm, it may be time to offer another one soon.`],
      learning: ['Lotti is learning your rhythm', 'No comparison needed yet', `Track ${n}'s sleep and feeds for a few days. After three comparison days, Lotti can use your own rhythm instead of general thresholds.`],
      all_good: ['Things are going smoothly today', 'Everything is in the usual range', `${n}'s day looks nicely balanced – sleep, feeds, and diaper changes are within your usual range. Enjoy your day together!`],
    },
    es: {
      hot_low_feeding: ['Importante hoy', 'Ofrece tomas con más frecuencia', `${n} ha bebido un poco menos de lo habitual y hará calor. Ofrece pecho o biberón con más frecuencia; en días calurosos puede venir bien un poco más.`],
      hot_low_sleep: ['Importante hoy', 'Un sueño fresco y tranquilo', `${n} ha dormido algo menos hoy y hará bochorno. El calor puede alterar el sueño; una habitación fresca y tranquila puede ayudaros.`],
      hot: ['Importante hoy', 'Protección frente al sol y el calor', `Hoy hará calor. Mantén a ${n} fuera del sol directo, usa ropa ligera y ofrece tomas algo más a menudo.`],
      high_uv: ['Importante hoy', 'Recuerda la protección solar', `El índice UV llegará a ${signals.weather.uvIndex ?? '–'} hoy. La sombra, un sombrero y ropa ligera y larga son la mejor protección para ${n}; evita el sol del mediodía.`],
      cold: ['Importante hoy', 'Una capa más y gorro', `Hoy refrescará. Una capa adicional y un gorro ayudarán a mantener a ${n} a una temperatura agradable.`],
      low_sleep: ['Importante hoy', 'Adelanta un poco el próximo sueño', `${n} ha dormido algo menos de lo habitual. Quizá convenga adelantar el próximo sueño y, si puedes, descansar tú también.`],
      rain_likely: ['Conviene saberlo hoy', 'Prepárate para la lluvia', `La previsión indica un ${rain} % de lluvia. Lleva el protector del cochecito o disfrutad de un día tranquilo en casa.`],
      low_feeding: ['Importante hoy', 'Quizá toque ofrecer otra toma', `${n} lleva ${signals.feeding.totalCount} tomas. Según vuestro ritmo habitual, quizá sea buen momento para ofrecer otra pronto.`],
      learning: ['Lotti está aprendiendo vuestro ritmo', 'Aún no hace falta comparar', `Registra durante unos días el sueño y las tomas de ${n}. Tras tres días de comparación, Lotti podrá usar vuestro propio ritmo.`],
      all_good: ['Hoy todo va bien', 'Todo dentro de vuestro rango habitual', `El día de ${n} parece equilibrado: sueño, tomas y cambios de pañal están dentro de lo habitual. ¡Disfrutad del día!`],
    },
  };
  const found = values[locale as Exclude<AppLocale, 'de'>]?.[id] ?? values.en.learning;
  return { id, tone: id === 'all_good' ? 'positive' : 'gentle', emoji: id.includes('sleep') ? '🌙' : id.includes('feeding') ? '🍼' : '🌿', title: found[0], headline: found[1], body: found[2] };
};

export const localizeAdvisorAnalysis = (locale: AppLocale, analysis: AdvisorAnalysis, signals: DailySignals): AdvisorAnalysis => {
  if (locale === 'de') return analysis;
  const temp = signals.weather.temperature ?? '–';
  const cardLabels = { sleep: translateAdvisor(locale, 'sleep'), feeding: translateAdvisor(locale, 'feeding'), diaper: translateAdvisor(locale, 'diaper'), weather: translateAdvisor(locale, 'weather') };
  const cards = analysis.cards.map((card) => ({ ...card, label: cardLabels[card.key], value: card.key === 'sleep' ? duration(signals.sleep.minutes, locale) : card.value, caption: card.isReal ? (locale === 'es' ? 'Registrado hoy' : 'Recorded today') : (locale === 'es' ? 'Aún sin registros' : 'Nothing recorded yet') }));
  const history = analysis.history.map((item) => localizedInsight(locale, item.id.replace(/^h_/, ''), signals));
  const main = localizedInsight(locale, analysis.main.id, signals);
  const reasons = locale === 'es'
    ? [`Basado en vuestro ritmo personal`, `Tiempo previsto: ${temp}°`, `${signals.feeding.totalCount} tomas registradas hoy`]
    : [`Based on your personal rhythm`, `Forecast temperature: ${temp}°`, `${signals.feeding.totalCount} feeds recorded today`];
  return { main, reasons, history, cards };
};

export const localizeStoredAdvisorInsight = (locale: AppLocale, item: AdvisorHistoryItem): AdvisorHistoryItem => {
  if (locale === 'de') return item;
  const topic = item.ruleId.includes('sleep') ? translateAdvisor(locale, 'sleep') : item.ruleId.includes('feed') ? translateAdvisor(locale, 'feeding') : item.ruleId.includes('diaper') ? translateAdvisor(locale, 'diaper') : translateAdvisor(locale, 'weather');
  return { ...item, title: topic, headline: locale === 'es' ? `Consejo anterior: ${topic}` : `Previous ${topic.toLowerCase()} insight`, body: locale === 'es' ? 'Este consejo se creó antes de cambiar el idioma. Los nuevos consejos aparecerán completamente traducidos.' : 'This insight was created before the language changed. New insights will appear fully translated.' };
};
